### ISSUE TITLE
How to append a new dataset to a file

### ISSUE THREAD

**Issue by elaidad57** [NeurodataWithoutBorders/matnwb#109]
PyNWB has an input to the read function that that specifies wether you want to read the file with the intentions of appending when writing, as opposed to overwriting. Does such a functionality exist in matnwb?

Thanks!

**Comment by ln-vidrio** [comment]
Not at the moment, unfortunately.  Direct interface with the actual file is limited to reading and writing only (for now).  However, the lower level HDF5 calls DO exist in MATLAB.
