### ISSUE TITLE
Trial Data Load Issues

### ISSUE THREAD

**Issue by owoolnough** [NeurodataWithoutBorders/matnwb#114]
Had an issue while loading data from an NWB file I created for EPhys data. Loaded for a fixed time window around trial start times. Errors out as some trials come back as 1100x1 and some 1101x1. Think I found the culprit:
+util/loadTimeSeriesData line 74
Changed from: count(end) = ceil((end_ind - start_ind) / downsample_factor);
To:    count(end) = round((end_ind - start_ind) / downsample_factor);
This seems to fix it.

Additionally, having troubles with selecting trials satisfying multiple conditions using conditions = containers.Map('correct',1). This only seems to work if it's given a single logical test and doesnt handle combinations e.g. conditions = containers.Map('correct',1,'reaction',1).

**Comment by bendichter** [comment]
thanks for the bug report, @owoolnough! I'm glad to see you are using these functions. It would be even more helpful if you could provide a minimal example of code that produces the issue and copy/paste the error message as well. Feel free to take a stab at this and issue a pull request, or I'll look into this when I get a chance.

**Comment by bendichter** [comment]
@owoolnough the proper syntax would be `containers.Map({'correct', 'reation'}, [1,1])` (though I wish it was your way. I think your way is more intuitive)
