### ISSUE TITLE
Improve tab completion if possible

### ISSUE THREAD

**Issue by mcafaro** [NeurodataWithoutBorders/matnwb#12]
Tab completion is an important part of discovery (for me at least). However, with all the subsref and properties trickiness, tab completion no longer works when you're navigating deeply within a hierarchy:
```matlab
>> f = nwbfile;
>> ts = types.TimeSeries;
>> f.acquisition.timeseries = types.untyped.Group;
>> f.acquisition.timeseries.test_timeseries = ts;
>> f.acquisition.timeseries.  % Tab completion says "No Completions Found" here
```
It would be great if this worked. It may not be possible but maybe someone can investigate it.

**Comment by ln-vidrio** [comment]
As of now, there is almost no subsref used in matnwb so tab completion in classes work intuitively.  The only aspect limiting tab completion is found in constrained Set objects which are map-backed.  The new elision rules in MatNWB 0.2.1 onwards also helps in flattening the hierarchy in general.
