### ISSUE TITLE
New doc and title keys in namespace spec files

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/matnwb#121]
I wanted to make you aware of a change in the specification language. In the schema portion of the namespace yaml we now allow users to provide for the source files an additional ``title`` and ``doc``. This change was made to allow us to standardize the generation of documentation for the schema more easily with the goal to improve support for extensions. We added the corresponding fields in the core NWB:N Namespace as well. This change only affects the specification of the Namespace YAML but does not affect the actual schema of the types in the actual source YAML files. MatNWB can probably just ignore those additional keys, so this may be simple no-op for MatNWB if that's what MatNWB is already doing. The ``title`` and ``doc`` key for the source files are mainly useful for documentation. Here the pull request on PyNWB with the changes in YAML:  https://github.com/NeurodataWithoutBorders/pynwb/pull/854/files

**Comment by ln-vidrio** [comment]
tested: 804afd71b98642af87fe697d2cfa9bded8e99a63
