### ISSUE TITLE
ExternalLink with extension error

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#122]
Working with [these](https://drive.google.com/drive/folders/15k47xIfK1mIAL1yGv-it5t_5OoyQcmbJ?usp=sharing) files and [this](https://github.com/bendichter/nwbext_ecog) extension

This works:

```matlab
>> generateExtension('path/to/ecog.namespace.yaml');
>> nwb = nwbRead('/Users/bendichter/Desktop/Chang/data/EC125/EC125.nwbaux');
>> nwb.general_subject

ans = 

  ECoGSubject with properties:

    cortical_surfaces: [1×1 types.ecog.CorticalSurfaces]
                  age: []
        date_of_birth: []
          description: []
             genotype: []
                  sex: []
              species: []
           subject_id: 'EC125'
               weight: []
                 help: 'Information about the subject'
```

But when I try access through a link I get this error:

```matlab
>> nwb = nwbRead('/Users/bendichter/Desktop/Chang/data/EC125/EC125_B22.nwb');
>> nwb.general_subject

ans = 

  ExternalLink with properties:

    filename: '/Users/bendichter/Desktop/Chang/data/EC125/EC125.nwbaux'
        path: '/general/subject'

>> nwb.general_subject.deref
Error using types.untyped.ExternalLink/deref (line 17)
Externally linked /Users/bendichter/Desktop/Chang/data/EC125/EC125.nwbaux/general/subject contains an unsupported
type.
```

I am now realizing that the link here is absolute, which might make it difficult to share this data and to reproduce this error.

**Comment by ln-vidrio** [comment]
At the current moment, classes in groups cannot be dereferenced through external links; it will only work on raw datasets stored externally as there's no guarantee that the external link is a NWB file (though it assumes that it is a HDF5 file).

I'll take a look at improving this.

**Comment by bendichter** [comment]
Oh, I see. OK yeah that would be great. Thanks for looking into this!
