### ISSUE TITLE
Group constructor accepts struct but only functions correctly with StructMap

### ISSUE THREAD

**Issue by mcafaro** [NeurodataWithoutBorders/matnwb#13]
It is much less verbose to create structs in MATLAB than StructMaps, for example:
```matlab
>> s.datasets.d1 = [1 2 3];
```
vs.
```matlab
>> s = util.StructMap('datasets', util.StructMap('d1', [1 2 3]));
```
But it you pass the former into the Group constructor, it will accept it and fail later if you do a subsref or subsasgn:
```matlab
>> s.datasets.d1 = [1 2 3];
>> g = types.untyped.Group(s);
>> g.d1
Reference to non-existent field 'map'.

Error in types.untyped.Group/findsubprop (line 124)
          if ~isempty(obj.(pn)) && isKey(obj.(pn).map, nm)

Error in types.untyped.Group/subsref (line 46)
          pn = findsubprop(obj, mainsub);
```
A good practice might be, rather than attempting to account for struct vs StructMap throughout the code, convert all structs to StructMaps when they are received from the user. Then the rest of the code can assume everything is a StructMap.

**Comment by ln-vidrio** [comment]
As of 418f8e6180c096aba530320c956dfd2820598090, neither Groups nor StructMaps used in matnwb.
