### ISSUE TITLE
Can't assign values to 'vectordata' field in a TimeIntervals object

### ISSUE THREAD

**Issue by mpompolas** [NeurodataWithoutBorders/matnwb#135]
I'm trying to assign some values on the vectordata field on some trial data and it never gets saved.

Example call:
vectordata_trials = types.untyped.Set('blablabla',111);
intervals_trials = types.core.TimeIntervals('vectordata',vectordata_trials)

Any ideas?
Thanks

**Comment by bendichter** [comment]
```matlab
>> blablabla = types.core.VectorData('data', [1,1,1], 'description', 'blablabla');
intervals_trials = types.core.TimeIntervals();
intervals_trials.vectordata.set('blablabla',blablabla);
>> intervals_trials.vectordata

ans = 

  Set with properties:

    blablabla: [types.core.VectorData]
```

**Comment by bendichter** [comment]
see example [here](https://neurodatawithoutborders.github.io/matnwb/tutorials/html/ecephys.html#13) for more details

**Comment by mpompolas** [comment]
Thanks, it confused me that the initialization of theTimeIntervals shows the vectordata as types.untyped.Set:

types.core.TimeIntervals

ans = 

  TimeIntervals with properties:

          start_time: []
           stop_time: []
                tags: []
          tags_index: []
          timeseries: []
    timeseries_index: []
            colnames: []
         description: []
                  id: []
          vectordata: [1×1 types.untyped.Set]
         vectorindex: [1×1 types.untyped.Set]
                help: 'A general epoch object'
