### ISSUE TITLE
Trial length not checked

### ISSUE THREAD

**Issue by owoolnough** [NeurodataWithoutBorders/matnwb#139]
Found a potential issue in types.core.TimeIntervals that could do with a warning/check. Using this to set trial details will accept trial definitions with unequal lengths e.g.:

trials = types.core.TimeIntervals( ...
            ...
            'start_time', types.core.VectorData('data', [1:1000],'description','start time of trial'),...
            'stop_time', types.core.VectorData('data', [1:500],'description','end time of trial'),...
            );

This will export fine but will not load trials out when imported

**Comment by ln-vidrio** [comment]
Since MatNWB has no internal knowledge of the intended DynamicTable Structure, it may be recommended to use #111 when that gets completed.

**Comment by nclack** [comment]
Closing in favor of #111 which will address this issue.
