### ISSUE TITLE
NWBFile.nwb_version not assigned

### ISSUE THREAD

**Issue by mcafaro** [NeurodataWithoutBorders/matnwb#14]
I would expect NWBFile.nwb_version to be assigned by MatNWB and not the user. Right now this is left blank unless the user specifies it. PyNWB assigns this version.

***Failing test:***
```matlab
>> nwbtest('Name', 'tests.system.NWBFileIOTest/testInFromPyNWB')
```

**Comment by ln-vidrio** [comment]
As of 418f8e6180c096aba530320c956dfd2820598090 and nwb-schema's 6a150431cc82c27cce5a9f869d6381201a5a97f5, nwb_version should be auto-assigned by the schema itself.
