### ISSUE TITLE
Different standards for TwoPhotonSeries and PlaneSegmentation's "image_mask"

### ISSUE THREAD

**Issue by kelsonSS** [NeurodataWithoutBorders/matnwb#142]
For the Ophys pipeline the raw data that is stored in TwoPhotonSeries is required to be in a Nframes  by Y by X  matrix while the ROI segmentation is in a NCells by X by Y matrix. This will cause errors and I suggest standardizing to the Nframes by X by Y format. 

This problem persists with 3D data and should be standardized to N by X by Y by Z

**Comment by oruebel** [comment]
Is this a MatNWB-specific issue or is this an issue with the NWB:N schema?

**Comment by ln-vidrio** [comment]
This does seem to be a schema-level issue.
https://github.com/NeurodataWithoutBorders/nwb-schema/issues/262
