### ISSUE TITLE
test: file_created_date causing problem

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#148]
when I run testnwb I get a bunch of the following errors:

```matlab
Verification failed in tests.unit.multipleShapesTest/testMultipleNullShapesDataset.

    ----------------
    Test Diagnostic:
    ----------------
    Values for property 'file_create_date' are not equal

    ---------------------
    Framework Diagnostic:
    ---------------------
    verifyEqual failed.
    --> The character arrays are not equal.
    
    Actual char:
        2019-05-16T13:02:17.007883-04:00
    Expected char:
        2019-05-16T13:02:17.007881-04:00
```

This is due to the slight time delay in creating two different `NWBFile` objects. Could we assign these datetimes instead of generating them automatically so that this test does not fail?

**Comment by ln-vidrio** [comment]
I've run into this issue before but when I run `nwbtest` all the tests pass.

**Comment by ln-vidrio** [comment]
Is this still reproducible?  Running nwbtest on the tip of master doesn't seem to fail this test.

**Comment by lawrence-mbf** [comment]
closed, stale.
