### ISSUE TITLE
Matrices are transposed on round trip to disk

### ISSUE THREAD

**Issue by mcafaro** [NeurodataWithoutBorders/matnwb#15]
Datasets are transposed after being written to disk by nwbExport and read back by nwbRead:
```matlab
    Actual Value:
         0     1     2     3     4     5     6     7     8     9
    Expected Value:
         0
         1
         2
         3
         4
         5
         6
         7
         8
         9
```
I believe this is because nwbExport transposes the matrices but nwbRead does not transpose them back.

**Failing test:**
```matlab
>> nwbtest('Name', 'tests.system.TimeSeriesIOTest/testRoundTrip')
```

**Comment by ln-vidrio** [comment]
fixed with 418f8e6180c096aba530320c956dfd2820598090
