### ISSUE TITLE
read error file with extension that contains dashes

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#153]
Error when trying to read file with types from namespace ("ndx-simulation-output"). In pynwb we substitute underscores for dashes in these cases.

```matlab
Undefined variable "types" or class "types.ndx".

Error in io.parseGroup (line 72)
    parsed = eval([typename '(kwargs{:})']);

Error in io.parseGroup (line 33)
    subg = io.parseGroup(filename, group, blacklist);

Error in io.parseGroup (line 33)
    subg = io.parseGroup(filename, group, blacklist);

Error in nwbRead (line 41)
    nwb = io.parseGroup(filename, info, blacklist);
```

**Comment by ln-vidrio** [comment]
There should be generated extension types under types.core.ndx-simulation-output.  Is that there?

**Comment by bendichter** [comment]
yes

**Comment by bendichter** [comment]
I'm working on uploading the file so you can easily reproduce the error

**Comment by bendichter** [comment]
```matlab
72      parsed = eval([typename '(kwargs{:})']);
K>> typename

typename =

    'types.ndx-simulation-output.CompartmentSeries'
```

**Comment by bendichter** [comment]
this file: https://drive.google.com/file/d/10NWcKKa4QAA1Qh_9p6weMPJ75kAE_Swl/view?usp=sharing

**Comment by ln-vidrio** [comment]
So I believe reading should work in #154 but I'm unable to test class generation as I don't see a cached spec in this file.  I'm pretty sure it would be wrong too as the generated class will be under +types/ndx-simulation-output/ as well.

**Comment by bendichter** [comment]
ok let me test. And I'll output the file with a cached spec

**Comment by bendichter** [comment]
I uploaded the file with a cached spec at the same location: https://drive.google.com/file/d/10NWcKKa4QAA1Qh_9p6weMPJ75kAE_Swl/view?usp=sharing. In #154 the read error changed to 

```matlab
Error using types.util.checkUnset (line 14)
Properties {Compartments} are not valid property names.

Error in types.ndx_simulation_output.SimulationMetaData (line
27)
            types.util.checkUnset(obj,
            unique(varargin(1:2:end)));

Error in io.parseGroup (line 72)
    parsed = eval([typename '(kwargs{:})']);

Error in io.parseGroup (line 33)
    subg = io.parseGroup(filename, group, blacklist);

Error in io.parseGroup (line 33)
    subg = io.parseGroup(filename, group, blacklist);

Error in nwbRead (line 41)
    nwb = io.parseGroup(filename, info, blacklist);
```

**Comment by ln-vidrio** [comment]
It looks like the property being assigned to SimulationMetaData is "Compartments" instead of "compartments".  Does pynwb automatically remove uppercase properties as well?  Uppercase property names are valid in MATLAB.

**Comment by bendichter** [comment]
hmm it looks like this might be an issue on the pynwb side. I set the name of SimulationMetaData.Compartments to compartments but it doesn't look like that is catching
