### ISSUE TITLE
Do not write datasets to HDF5 if they are unassigned

### ISSUE THREAD

**Issue by mcafaro** [NeurodataWithoutBorders/matnwb#16]
PyNWB only writes datasets to HDF5 if they have been set. MatNWB writes all datasets to disk even if they have not been assigned/set by the user or a default value. I'm not sure if this discrepancy will cause issues in the future but it is inefficient to create these empty datasets and it means you have a bunch of empty datasets crowding up the HDF5 file (not great when viewed in HDFView for instance).

**Comment by ln-vidrio** [comment]
This is no longer true as of `v0.2.1`
