### ISSUE TITLE
new scratch group breaks elide

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#169]
The new addition of the scratch group to the core schema:

https://github.com/NeurodataWithoutBorders/nwb-schema/blob/da3bcd72d63c83c512dd56e9959f409230c5756e/core/nwb.file.yaml#L77-L94

breaks the elide rules and triggers the `keyboard;` on line 232. I was able to fix this with a hack, adding `&& ~strcmp(sub.name, 'scratch')` to  `+file/Group.m` line 226, but I'm sure there's a better way to do this.

**Comment by ln-vidrio** [comment]
should be resolved by #172
