### ISSUE TITLE
Schema should be a submodule

### ISSUE THREAD

**Issue by mcafaro** [NeurodataWithoutBorders/matnwb#17]
The schema files have currently been copied and pasted into the MatNWB repository. A better approach may be to use a submodule that points to the schema repo. I can think of some pros/cons for both approaches, so this change is not a definite win but something to think about. Submodule pros: avoids copy/paste mistakes, makes the source of the schema files clear (as well as git rev). Cons: confusing for new users cloning the repo (need to use --recursive flag to get submodules)

**Comment by ln-vidrio** [comment]
Since we now have users that rely on the source code without using git, we can no longer implement this suggested enhancement without breakage.
