### ISSUE TITLE
Namespaces problem

### ISSUE THREAD

**Issue by mpompolas** [NeurodataWithoutBorders/matnwb#170]
Hi, I'm trying to access a file that @bendichter shared with me but I get a namespace error for a dependencies field:

nwb2 = nwbRead('F:/Buffalo/2017_4_27_v2_processed.nwb')
Reference to non-existent field 'dependencies'.

Error in schemes.loadNamespace (line 7)
ancestry = schemes.Namespace.empty(length(Cache.dependencies), 0);

Error in schemes.loadNamespace (line 11)
    ancestry(i) = schemes.loadNamespace(ancestorName);

Error in file.writeNamespace (line 3)
Namespace = schemes.loadNamespace(namespaceName);

Error in spec.generate (line 33)
file.writeNamespace(NamespaceInfo.name);

Error in nwbRead>generateSpec (line 83)
    spec.generate(namespaceText, schemaMap);

Error in nwbRead>checkEmbeddedSpec (line 44)
    generateSpec(fid, h5info(filename, specLocation));

Error in nwbRead (line 27)
    specLocation = checkEmbeddedSpec(filename);

@ln-vidrio can  you please take a look at this?
Here's the link to the file:
https://drive.google.com/open?id=1-R5SJ9ZeoqxZxlNqFQ1OFRn7Nmyj3gvC

Thanks

**Comment by ln-vidrio** [comment]
It looks like I need permission to access the drive file.  Can you grant access to lawrence@vidriotech.com?

**Comment by bendichter** [comment]
@ln-vidrio done

**Comment by ln-vidrio** [comment]
The schema looks strange.  Was this file generated using pynwb?

**Comment by bendichter** [comment]
Yeah. Strange how?

**Comment by ln-vidrio** [comment]
For one, `core` is dependent on a `hdmf-commons`.  There was a bug in matnwb that didn't factor in the dash but I've since fixed that.

More importantly, `hdmf-commons` doesn't use `neurodata_type_def` or `neurodata_type_inc`, instead opting for `data_type_def` and `data_type_inc`.  Are these intended to be a new way to specify types?  This caused dependency issues as MatNWB assumed the only name for type/parent declarations are `neurodata_type_def` and `neurodata_type_inc` respectively.  I've fixed this on my end but I'm wondering if that is intended for future compatibility's sake.

**Comment by bendichter** [comment]
Yes, we definitely should have run that change by you. Essentially, the idea is to make the HDMF infrastructure more general-purpose so it can be used in projects outside of NWB. So some of the neurodata_types that defined general structural components and were not tied to neuroscience were moved to `hdmf-commons`. There, it wouldn't make sense to use the term `neurodata_type`, so instead they used the term `data_type`.

**Comment by ln-vidrio** [comment]
The immediate issues have been resolved but I have opted to place these changes in the unstable todo/update_schema branch for now as the file is technically still not readable due to #169

**Comment by bendichter** [comment]
@ln-vidrio I am trying to work with todo/update_schema but when I run `generateCore` I do not see any new classes in the +types folder.

**Comment by ln-vidrio** [comment]
This is probably due to the unstable changes at the tip of this branch.  @bendichter can you go to the commit immediately before the tip of this branch and check if that works?  If so, I'll go ahead and revert the change.

**Comment by ln-vidrio** [comment]
Should be 2c0a852

**Comment by lawrence-mbf** [comment]
Looking at the linked issue, this appears to be fixed.
