### ISSUE TITLE
update paths

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#173]
`generateCore` currently expects paths `schema/core/nwb.namespace.yaml` and `schema/common/namespace.yaml`. 

`git clone https://github.com/NeurodataWithoutBorders/nwb-schema.git`

creates filepath `nwb-schema/core/nwb.namespace.yaml` and the core is missing because you need to call `git clone` in recursive mode. If you correct that, calling instead 

`git clone --recursive https://github.com/NeurodataWithoutBorders/nwb-schema.git`

you also get path `nwb-schema/hdmf-common-schema/common/namespace.yaml`. In order to update our code to the current schema, we need to 

1. Change the git clone call to be recursive
2. Update the filepaths in `generateCore`

**Comment by bendichter** [comment]
We could also do what pynwb does and attach nwb-schema as a submodule at a specific commit. What do you think of that, @ln-vidrio

**Comment by ln-vidrio** [comment]
The only hangup against moving to submodules is that users who are using git to manage matnwb must know that submodules now exist, otherwise their schemas will never actually be updated.  I have no idea how many users are actually using this method though.
