### ISSUE TITLE
Generated class constructor should error when given an unknown argument 

### ISSUE THREAD

**Issue by mcafaro** [NeurodataWithoutBorders/matnwb#18]
The generated (written by writeClass) class constructor currently ignores unknown key-value pairs. It should probably error (or at least warn) to alert the user:
```matlab
>> ts = types.TimeSeries('unknown_key', 2);  % unknown_key is simply ignored
```
It is very easy to misspell a key and think you set the value but you did not:
```matlab
>> ts = types.TimeSeries('decription', 2); % meant to set description but there is a type-o
```
**Filtered test:**
```matlab
>> nwbtest('ProcedureName', 'testWriteClassConstructorThrowsOnUnknownArgument')
```

**Comment by ln-vidrio** [comment]
Erroring on unknown key-value pairs causes problems with extensions which inherit and add their own fields.  There's no guarantee that an unknown key-value pair is not simply a subclass-specific property.

One could create a filterable warning that can be hidden when a subclass calls the superclass constructor, thus only showing a warning if the constructor was not called by a subclass.

**Comment by ln-vidrio** [comment]
This is fixed now.
