### ISSUE TITLE
Improve Iterative Write Workflow

### ISSUE THREAD

**Issue by ln-vidrio** [NeurodataWithoutBorders/matnwb#184]
After #179 the ability to write to datasets iteratively is now possible.  However, it still requires exporting the file and "amending" the dataset which is awkward.

The path forward right now would be to provide a rudimentary Generator class that must be subclassed by the user in order to migrate the data into the NWB format.

**Comment by bendichter** [comment]
and a tutorial, please!

**Comment by bendichter** [comment]
@ln-vidrio close this?
