### ISSUE TITLE
Inherited dataset where the dtype is redefined to be more specific dtype causes error with validation function

### ISSUE THREAD

**Issue by mcafaro** [NeurodataWithoutBorders/matnwb#19]
When a dataset is inherited and its dtype is "any", then the inheriting type redefines it as something more specific, like "text", this causes the generated class to error on instantiation because the default value is assigned per the dtype of the superclass dataset but the validation function is based on the dtype of the dataset in the actual class.

For example, AnnotationSeries inherits from TimeSeries. TimeSeries.data has a dtype of "any". AnnotationSeries.data has a dtype of "text". The generated types.AnnotationSeries fails during construction:
```matlab
>> types.AnnotationSeries
Error using types.AnnotationSeries/validate_data (line 64)
AnnotationSeries: data must be a cell string

Error in types.TimeSeries/set.data (line 99)
      obj.data = validate_data(obj, val);

Error in types.TimeSeries (line 71)
            obj.(field) = p.Results.(field);

Error in types.AnnotationSeries (line 32)
      obj = obj@types.TimeSeries(varargin{:});
```
**Failing test:**
```matlab
>> nwbtest('ProcedureName', 'testSmokeInstantiateCore')
```

**Comment by ln-vidrio** [comment]
418f8e6180c096aba530320c956dfd2820598090 fixed.  Default values are now narrowed by [], types.untyped.Set, and types.untyped.Anon.  Furthermore, type checking ignores empty values (required values are checked on export instead).
