### ISSUE TITLE
Can not assign DataPipe type to plane_segmentation.image_mask

### ISSUE THREAD

**Issue by IvanSmal** [NeurodataWithoutBorders/matnwb#192]
image_mask has to be types.hdmf_common.VectorData

this type seems to only accept 'raw' data into the 'data' field. THis makes it impossible to add data as types.untyped.DataPipe

[error log.txt](https://github.com/NeurodataWithoutBorders/matnwb/files/4363191/error.log.txt)

**Comment by bendichter** [comment]
@IvanSmal Can you please show a small segment of code that reproduces this error, along with the error message?

**Comment by IvanSmal** [comment]
Error log is attached to the original message as a .txt
Let me create a small script that reproduces that error

**Comment by IvanSmal** [comment]
attached is a script that reproduces the error
[reproduce_error.txt](https://github.com/NeurodataWithoutBorders/matnwb/files/4363401/reproduce_error.txt)

**Comment by IvanSmal** [comment]
'''
%% reproducing image mask dataPipe error

nwbfile_input_args={'keywords',[],'session_start_time','2020-01-18 00:00:00','identifier','ident1','session_description','fdsfsfdsfd'};
nwb=NwbFile(nwbfile_input_args{:});

fpath='erroredout';

numOfPlanes=1;

op_input_args={'emission_lambda',200,'description','desc1'};
optical_channel = types.core.OpticalChannel(op_input_args{:});

ip_input_args={'description','ImgPlane1','excitation_lambda',200,...
    'imaging_rate',5,'indicator','ind1','location','brain'};

ps_input_args={'description','test'};

imaging_plane{1} = types.core.ImagingPlane('device', ...
        types.untyped.SoftLink(['/general/devices/' 'imaging_plane']), ...
        'optical_channel', optical_channel, ip_input_args{:});
    
nwb.general_optophysiology.set('ImagingPlane', imaging_plane{1});

image_masks=randi(100,250,250,451);

%% below is code directly from the offending function, with appropriate data faked
ophys_module = types.core.ProcessingModule(...
    'description', 'holds processed calcium imaging data');

img_seg = types.core.ImageSegmentation();

for i=1:numOfPlanes
%     ps_input_args = get_input_args(metadata.Ophys.ImageSegmentation.plane_segmentations{i}, '');
    plane_segmentation{i} = types.core.PlaneSegmentation( ...
        'imaging_plane', imaging_plane{i}, ...
        'colnames', {'imaging_mask'}, ...
        'id', types.hdmf_common.ElementIdentifiers('data', int64(0:256-1)), ...
        ps_input_args{:});
    
    maxSize=size(image_masks);
    
    DataPipe=types.untyped.DataPipe(maxSize,...
        'data', image_masks,...
        'dataType', 'uint64',...
        'compressionLevel', 5,...
        'chunkSize', [10 10],...
        'axis', 1);
    
    plane_segmentation{i}.image_mask =types.hdmf_common.VectorData(...
        'data',DataPipe, 'description', 'image masks');
    
    img_seg.planesegmentation.set('plane_segmentation',...
        plane_segmentation{i});
    
    plane_seg_object_view{i} = types.untyped.ObjectView( ...
        ['/processing/ophys/' 'ImageSegmentation' '/' 'PlaneSegmentation']);
end

ophys_module.nwbdatainterface.set('ImageSegmentation', img_seg);
nwb.processing.set('ophys', ophys_module);

nwbExport(nwb, fpath);
'''

**Comment by IvanSmal** [comment]
~~~
%% reproducing image mask dataPipe error

nwbfile_input_args={'keywords',[],'session_start_time','2020-01-18 00:00:00','identifier','ident1','session_description','fdsfsfdsfd'};
nwb=NwbFile(nwbfile_input_args{:});

fpath='erroredout';

numOfPlanes=1;

op_input_args={'emission_lambda',200,'description','desc1'};
optical_channel = types.core.OpticalChannel(op_input_args{:});

ip_input_args={'description','ImgPlane1','excitation_lambda',200,...
    'imaging_rate',5,'indicator','ind1','location','brain'};

ps_input_args={'description','test'};

imaging_plane{1} = types.core.ImagingPlane('device', ...
        types.untyped.SoftLink(['/general/devices/' 'imaging_plane']), ...
        'optical_channel', optical_channel, ip_input_args{:});
    
nwb.general_optophysiology.set('ImagingPlane', imaging_plane{1});

image_masks=randi(100,250,250,451);

%% below is code directly from the offending function, with appropriate data faked
ophys_module = types.core.ProcessingModule(...
    'description', 'holds processed calcium imaging data');

img_seg = types.core.ImageSegmentation();

for i=1:numOfPlanes
%     ps_input_args = get_input_args(metadata.Ophys.ImageSegmentation.plane_segmentations{i}, '');
    plane_segmentation{i} = types.core.PlaneSegmentation( ...
        'imaging_plane', imaging_plane{i}, ...
        'colnames', {'imaging_mask'}, ...
        'id', types.hdmf_common.ElementIdentifiers('data', int64(0:256-1)), ...
        ps_input_args{:});
    
    maxSize=size(image_masks);
    
    DataPipe=types.untyped.DataPipe(maxSize,...
        'data', image_masks,...
        'dataType', 'uint64',...
        'compressionLevel', 5,...
        'chunkSize', [10 10],...
        'axis', 1);
    
    plane_segmentation{i}.image_mask =types.hdmf_common.VectorData(...
        'data',DataPipe, 'description', 'image masks');
    
    img_seg.planesegmentation.set('plane_segmentation',...
        plane_segmentation{i});
    
    plane_seg_object_view{i} = types.untyped.ObjectView( ...
        ['/processing/ophys/' 'ImageSegmentation' '/' 'PlaneSegmentation']);
end

ophys_module.nwbdatainterface.set('ImageSegmentation', img_seg);
nwb.processing.set('ophys', ophys_module);

nwbExport(nwb, fpath);
~~~

**Comment by IvanSmal** [comment]
error message that code gives:
~~~
Error using io.getBaseType (line 45)
Type `types.untyped.DataPipe` is not a support raw type

Error in io.mapData2H5 (line 9)
tid = io.getBaseType(class(data));

Error in io.writeDataset (line 4)
[tid, sid, data] = io.mapData2H5(fid, data, varargin{:});

Error in types.untyped.MetaClass/write_base (line 21)
                    io.writeDataset(fid, fullpath, obj.data,
                    'forceArray');

Error in types.untyped.MetaClass/export (line 63)
            refs = obj.write_base(fid, fullpath, refs);

Error in types.hdmf_common.Data/export (line 39)
        refs = export@types.untyped.MetaClass(obj, fid, fullpath,
        refs);

Error in types.hdmf_common.VectorData/export (line 42)
        refs = export@types.hdmf_common.Data(obj, fid, fullpath,
        refs);

Error in types.core.PlaneSegmentation/export (line 106)
            refs = obj.image_mask.export(fid, [fullpath
            '/image_mask'], refs);

Error in types.untyped.Set/export (line 177)
                    refs = v.export(fid, propfp, refs);

Error in types.core.ImageSegmentation/export (line 45)
            refs = obj.planesegmentation.export(fid, fullpath, refs);

Error in types.untyped.Set/export (line 177)
                    refs = v.export(fid, propfp, refs);

Error in types.core.ProcessingModule/export (line 74)
            refs = obj.nwbdatainterface.export(fid, fullpath, refs);

Error in types.untyped.Set/export (line 177)
                    refs = v.export(fid, propfp, refs);

Error in types.core.NWBFile/export (line 734)
            refs = obj.processing.export(fid, [fullpath
            '/processing'], refs);

Error in NwbFile/export (line 55)
                refs = export@types.core.NWBFile(obj, output_file_id,
                '/', {});

Error in nwbExport (line 35)
    export(nwb(i), filename);

Error in reproducing_error (line 62)
nwbExport(nwb, fpath);
~~~

**Comment by ln-vidrio** [comment]
@IvanSmal Does 6ab0739 resolve the problem?

**Comment by IvanSmal** [comment]
Yes, that resolved it. Thank you
