### ISSUE TITLE
Dataset with text dtype and null shape causes error with validation function

### ISSUE THREAD

**Issue by mcafaro** [NeurodataWithoutBorders/matnwb#20]
When a dataset has a text dtype and a multi-dimensional shape with a null dimension, the validation function will error when the generated class is instantiated.

For example, ElectrodeGroup has a channel_coordinates dataset with the following spec:
```yaml
    name: channel_coordinates
    shape:
    - null
    - 3
```
Trying to instantiate the generated class:
```matlab
>> types.ElectrodeGroup
Error using types.ElectrodeGroup/validate_channel_coordinates (line 147)
ElectrodeGroup.channel_coordinates: val must have shape [~,3]

Error in types.ElectrodeGroup/set.channel_coordinates (line 62)
      obj.channel_coordinates = validate_channel_coordinates(obj, val);

Error in types.ElectrodeGroup (line 54)
          obj.(field) = p.Results.(field);
```
**Failing test:**
```matlab
>> nwbtest('ProcedureName', 'testWriteDatasetWithNullShape')
```

**Comment by ln-vidrio** [comment]
TimeSeries.control_description has something like this but this is probably fixed:

1. Empty values are no longer type-checked as of 418f8e6180c096aba530320c956dfd2820598090.
2. typechecking for char includes cellstr as of a5e5de0f5520067dc912a8e5420b95ee2bf78884.

Will follow up with updated Tests.

**Comment by ln-vidrio** [comment]
New test under
`>> nwbtest('ProcedureName', 'testInheritedDtypeDataset')`
