### ISSUE TITLE
A class definition must be in an "@" directory

### ISSUE THREAD

**Issue by luiztauffer** [NeurodataWithoutBorders/matnwb#200]
os: windows 10
matlab: 2017a

I'm getting the following error when trying to open any nwb file:

```
Error using types.hdmf_common.DynamicTableRegion
Error: File: DynamicTableRegion.m Line: 1 Column: 10
A class definition must be in an "@" directory.

Error in io.parseDataset (line 76)
    parsed = eval([typename '(kwargs{:})']);

Error in io.parseGroup (line 22)
    dataset = io.parseDataset(filename, datasetInfo, fullPath, Blacklist);

Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);

Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);

Error in nwbRead (line 33)
nwb = io.parseGroup(filename, h5info(filename), Blacklist);
```

The `DynamicTableRegion` here is just one instance of the same error that would appear for other classes if I try to open other files.

**Comment by ln-vidrio** [comment]
Hi luiz, is there a "@" character in your current working directory path by any chance?
If not, can you run `which('types.hdmf_common.DynamicTableRegion', '-all')` and respond with the resulting path?

**Comment by luiztauffer** [comment]
Hi In-vidrio,
there's no @ character in the paths. If I run this command, I get the following:
```
C:\Users\Luiz\Google Drive (luiz@taufferconsulting.com)\client_ben\project_jaeger_lab\+types\+hdmf_common\DynamicTableRegion.m  % types.hdmf_common.DynamicTableRegion constructor
```

which is a +types directory that gets created locally when I run `generateCode()`

**Comment by ln-vidrio** [comment]
The `Google Drive...` path counts. See the linked answer below:
https://www.mathworks.com/matlabcentral/answers/84483-class-definition-directory-error#comment_292888

Use a directory that doesn't have the '@' symbol *anywhere* on the path.  I recreated the issue by placing my matnwb directory inside a directory with an `@` symbol and caused similar errors.

**Comment by ln-vidrio** [comment]
Another fix is to put your working directory in the matnwb root directory.  If you're doing that then it may be a different issue.

**Comment by ln-vidrio** [comment]
Side note, I think it works fine in 2019 versions of MATLAB.  Let me test 2017.

**Comment by luiztauffer** [comment]
agh!! thanks, I missed that!
you're right, I ran it in a '@' free path and it works! =)

**Comment by luiztauffer** [comment]
Should I close the Issue, or maybe this @ path problem could be stated somewhere? e.g. known errors or something

**Comment by ln-vidrio** [comment]
I'm investigating whether or not this has actually been fixed in 2019 as I have not been able to recreate it fully on my version.

I agree that a FAQ for this kind of stuff would be useful.  I May include in the README or elsewhere.
