### ISSUE TITLE
Heterogeneous Arrays not Supported

### ISSUE THREAD

**Issue by ln-vidrio** [NeurodataWithoutBorders/matnwb#212]
Particularly for Intracellular Ephys subclasses.
This can cause issues since MatNWB currently assumes that cell arrays are cellstrings.
It's currently not possible to create an array of `CurrentClampStimulusSeries` and `CurrentClampSeries` objects in MATLAB. You need a cell array.

**Comment by bendichter** [comment]
I don't think HDF5 supports heterogeneous arrays

**Comment by bendichter** [comment]
Do you mean compound datatypes?

**Comment by ln-vidrio** [comment]
@bendichter I should clarify. It's currently not possible to create an array of `CurrentClampStimulusSeries` and `CurrentClampSeries` objects in MATLAB. You need a cell array to store it. Right now, MatNWB assumes cell arrays are cell strings. I'm testing a fix right now where the MetaClass simply inherits from matlab.mixins.Heterogeneous so that this can be done.

**Comment by ln-vidrio** [comment]
Ah, I forget, that's having high-level types in an array doesn't make sense either. Nevermind.
