### ISSUE TITLE
Support for single-precision (32-bit) with `types.untyped.DataPipe`

### ISSUE THREAD

**Issue by bahanonu** [NeurodataWithoutBorders/matnwb#213]
Currently matnwb `types.untyped.DataPipe` does not support the `single` type for input data and the `datatype` and `data` are not checked to be of the same type.

The below gives the following error.
```MATLAB
types.untyped.DataPipe('datatype','double','data',single([1 1]));
```
```MATLAB
Error using types.untyped.datapipe.Configuration/set.dataType (line 80)
Datatypes must be one of the following:
float|double|uint8|int8|uint16|int16|uint32|int32|uint64|int64

Error in types.untyped.DataPipe (line 89)
                config.dataType = class(p.Results.data);
```

While the below works even though the `datatype` and `data` do not have the same class.
```MATLAB
types.untyped.DataPipe('datatype','single','data',double([1 1]));
```

**Comment by ln-vidrio** [comment]
Whoops, the `float` there should be `single` instead.

As for the second example, the class of the 'data' keyword argument overrides the `datatype` argument. Perhaps that should be a warning.

**Comment by bahanonu** [comment]
Sounds good, seems changing `float` to `single` at
https://github.com/NeurodataWithoutBorders/matnwb/blob/master/%2Btypes/%2Buntyped/%2Bdatapipe/Configuration.m#L40
solves the issue.

Good to know; a warning would be good in this case (e.g. letting know that `data` is overriding `datatype` if they disagree).
