### ISSUE TITLE
Error when running nwbRead - but not when setting a breakpoint

### ISSUE THREAD

**Issue by jens-k** [NeurodataWithoutBorders/matnwb#219]
I try to run the following code as part of a function:
```
nwb_fileversion = util.getSchemaVersion(filename);
generateCore;
tmp = nwbRead(filename);
```
Running that function  throws an error for the nwbRead call:
```
Error using types.core.TimeSeries
Method 'TimeSeries' is not defined for class 'types.core.TimeSeries' or is removed from MATLAB's search path.
Error in io.parseGroup (line 85)
    parsed = eval([Type.typename '(kwargs{:})']);
Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);
Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);
Error in nwbRead (line 33)
nwb = io.parseGroup(filename, h5info(filename), Blacklist);
Error in ft_read_header (line 2308)
	tmp = nwbRead(filename);
```
Running the two lines directly from the command window works.

When I create a breakpoint at the line of the call to nwbRead, executing the line ('Step') suddenly works. 
When I create the breakpoint one line later it doesn't.
When I create a breakpoint at the line before (util.getSchemaVersion) and continue manually from there, I get an error for the call to generateCore:
```
Error using rmdir
C:\Users\klinzing\Dropbox (Princeton)\_Project workspace\NWB\+types\+hdmf_common could not be removed.
Error in file.writeNamespace (line 7)
    rmdir(path, 's');
Error in generateExtension (line 30)
file.writeNamespace(Namespace.name);
Error in generateCore (line 31)
        generateExtension(commonPath);
Error in ft_read_header (line 2307)
    generateCore;
```

See a discussion on this here: https://nwb-users.slack.com/archives/C5XKC14L9/p1589501501194400

**Comment by jens-k** [comment]
When I create a function only containing these three lines I get the second error on execution about every 4th time.

**Comment by ln-vidrio** [comment]
This may have something to do with how MATLAB identifies packages in its namespace:
https://www.mathworks.com/help/matlab/ref/rehash.html
This of course will change based on where one breakpoints as I believe `rehash` may be dependent on when control is given to the user.

**Comment by jens-k** [comment]
Calling rehash after generateCore indeed seems to solve the problem!
