### ISSUE TITLE
MatNWB/PyNWB file incompatibility

### ISSUE THREAD

**Issue by mcafaro** [NeurodataWithoutBorders/matnwb#22]
Many of the tests writing a file in MatNWB and trying to open it in PyNWB fail. Most appear to fail because MatNWB writes empty datasets when the datasets have not been assigned/set by the user or a default value. PyNWB does not expect these empty datasets. Not sure if that’s considered a PyNWB or MatNWB issue.

**Failing tests:**
```matlab
>> nwbtest('Name', 'tests.system.*/*PyNWB')
```

**Comment by mcafaro** [comment]
Related to #16

**Comment by ln-vidrio** [comment]
This has been fixed.
