### ISSUE TITLE
Allow loading of non-continuous data segments (DataStub.load)

### ISSUE THREAD

**Issue by jens-k** [NeurodataWithoutBorders/matnwb#221]
The method types.untyped.DataStub.load allows addressing a data subset using indices. For example, data.load([23, 2063], [42, 2245]) would give you rows 23 to 42 and columns 2063 to 2245.

However, e.g., when the data represents an LFP, one might be interested in specific non-adjacent rows, i.e. channels. Currently, in order to minimize memory load, one needs to retrieve channel by channel or the first up to the last channel and subselect afterwards. Allowing the user to provide an array with desired channels would feel more natural.

https://nwb-users.slack.com/archives/C5XKC14L9/p1589494856175700

**Comment by bendichter** [comment]
See https://github.com/NeurodataWithoutBorders/matnwb/issues/120

**Comment by lawrence-mbf** [comment]
#259 fixes this issue
