### ISSUE TITLE
How to read in numerical data after iterative write with dataPipe?

### ISSUE THREAD

**Issue by GMCadode** [NeurodataWithoutBorders/matnwb#225]
Not sure what the appropriate method is. When working the example from the dataPipe tutorial the usual method for loading data as if from a dataStub doesn't work:

>> test = nwb.acquisition.get('time_series').data.load;
No appropriate method, property, or field 'load'
for class 'types.untyped.DataPipe'.

What is the appropriate call to read the data that was iteratively written using dataPipe?
Thanks

**Comment by ln-vidrio** [comment]
That's strange, everything after a1b12667868246c4d39dd01cbaaf3c4ebcc4daaa appears to have been erased.

For now, please use commit a1b12667868246c4d39dd01cbaaf3c4ebcc4daaa until we resolve the issue on the repository.

**Comment by ln-vidrio** [comment]
I've reverted those changes for now. Please re-pull from master on the repository.

**Comment by mpompolas** [comment]
Just got a similar issue after trying to load a DANDI Neuropixel dataset:

```
>> nwb2.acquisition.get('probe_810755801_lfp').electricalseries.get('probe_810755801_lfp_data').timestamps

ans = 

  DataPipe with properties:

            internal: [1×1 types.untyped.datapipe.BoundPipe]
                axis: 1
              offset: 11070604
            dataType: 'double'
           chunkSize: 10812
    compressionLevel: 9
          hasShuffle: 0

>> nwb2.acquisition.get('probe_810755801_lfp').electricalseries.get('probe_810755801_lfp_data').timestamps.load(1,10)
Unrecognized method, property, or field 'load' for class 'types.untyped.datapipe.BoundPipe'.

Error in types.untyped.DataPipe/load (line 231)
            data = obj.internal.load(varargin{:});
>> 
```

**Comment by ln-vidrio** [comment]
Whoops, DataPipe was recently removed from being a subclass, and now simply holds a reference to DataStub. @mpompolas Does the branch at #271 resolve the issue?

**Comment by mpompolas** [comment]
yeap, it worked
