### ISSUE TITLE
`namespace` searching hierarchy

### ISSUE THREAD

**Issue by lawrence-mbf** [NeurodataWithoutBorders/matnwb#233]
As per https://github.com/NeurodataWithoutBorders/matnwb/pull/232#issuecomment-653047751

This is the order in which MatNWB should search for the `namespace` directory\:

1. - [ ] Current working directory
2. - [ ]  Workspace environment
3. - [x] MatNWB directory
4. - [x] Warn that no namespace could be found.

**Comment by lawrence-mbf** [comment]
Revisiting this, I'm not sure if this should break from default MATLAB script discovery behavior. That way at least it's consistent and is not a strange mental load for users.

**Comment by ehennestad** [comment]
Adding this here for reference: [PR #556](https://github.com/NeurodataWithoutBorders/matnwb/pull/556)

**Comment by ehennestad** [comment]
@lawrence-mbf It is unclear how I could resolve this issue. Does this adress an existing problem in matnwb?

**Comment by lawrence-mbf** [comment]
If there was I do not recall why. I think the order in which the `namespace` directory was discovered was perhaps unintuitive? But that is my best guess. Feel free to close.
