### ISSUE TITLE
error reading Neuropixel file

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#238]
When opening [this Neuropixel file](https://girder.dandiarchive.org/api/v1/item/5eda859399f25d97bd27985d/download), I get the following error:

```matlab
>> clear;
>> generateCore();
>> nwb = nwbRead('/Volumes/easystore5T/data/Allen/neuropixel/sub-699733573_ses-715093703.nwb');
Error using types.util.checkUnset (line 13)
Unexpected properties {unit}.

Your schema version may be incompatible with the file.  Consider checking the schema
version of the file with `util.getSchemaVersion(filename)` and comparing with the YAML
namespace version present in nwb-schema/core/nwb.namespace.yaml

Error in types.hdmf_common.VectorData (line 26)
            types.util.checkUnset(obj, unique(varargin(1:2:end)));

Error in io.parseDataset (line 72)
    parsed = eval([Type.typename '(kwargs{:})']);

Error in io.parseGroup (line 22)
    dataset = io.parseDataset(filename, datasetInfo, fullPath, Blacklist);

Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);

Error in nwbRead (line 33)
nwb = io.parseGroup(filename, h5info(filename), Blacklist);
```

This file has a slightly older version of NWB

```python
>> util.getSchemaVersion('/Volumes/easystore5T/data/Allen/neuropixel/sub-699733573_ses-715093703.nwb')

ans =

  1×1 cell array

    {'2.2.2'}
```

so I tried downloading nwb-schema and checking out the proper version, but that did not fix the issue and resulted in the same error.

Trying pynwb's validation, there were errors, but not ones that look relevant here:

```bash
$ python -m pynwb.validate /Volumes/easystore5T/data/Allen/neuropixel/sub-699733573_ses-715093703.nwb
Validating /Volumes/easystore5T/data/Allen/neuropixel/sub-699733573_ses-715093703.nwb against cached namespace information using namespace ndx-aibs-ecephys.
 - found the following errors:
EcephysElectrodeGroup/has_lfp_data (general/extracellular_ephys/probeA.has_lfp_data): incorrect type - expected 'bool', got 'bool_'
EcephysElectrodeGroup/has_lfp_data (general/extracellular_ephys/probeB.has_lfp_data): incorrect type - expected 'bool', got 'bool_'
EcephysElectrodeGroup/has_lfp_data (general/extracellular_ephys/probeC.has_lfp_data): incorrect type - expected 'bool', got 'bool_'
EcephysElectrodeGroup/has_lfp_data (general/extracellular_ephys/probeD.has_lfp_data): incorrect type - expected 'bool', got 'bool_'
EcephysElectrodeGroup/has_lfp_data (general/extracellular_ephys/probeE.has_lfp_data): incorrect type - expected 'bool', got 'bool_'
EcephysElectrodeGroup/has_lfp_data (general/extracellular_ephys/probeF.has_lfp_data): incorrect type - expected 'bool', got 'bool_'
```

**Comment by ln-vidrio** [comment]
The VectorData units/waveform_mean has an unexpected attribute 'unit' which is not in the schema even for version '2.2.2'.
It looks to be only true for that specific VectorData so removing the 'unit' attribute will make that VectorData conformant.

I'm not sure what version VectorData had the 'unit' attribute but it doesn't exist by '2.2.2'.

**Comment by rly** [comment]
As of NWB 2.2.0:
> Added “sampling_rate” and “unit” attributes to “waveform_mean” and “waveform_sd” datasets/columns in Units table.

https://nwb-schema.readthedocs.io/en/stable/format_release_notes.html#january-6-2020

Is it not possible to load an attribute on a VectorData in this way in matnwb?

**Comment by ln-vidrio** [comment]
Not without neurodata_type_def unfortunately: https://github.com/NeurodataWithoutBorders/matnwb/issues/43

**Comment by ehennestad** [comment]
I have the NWB file for that session id and I can open it with matnwb / nwbRead. The file was downloaded from the Allen Brain Observatory S3 bucket and schema version is 2.2.2
