### ISSUE TITLE
lazy loading of datasets

### ISSUE THREAD

**Issue by nclack** [NeurodataWithoutBorders/matnwb#27]

**Comment by ln-vidrio** [comment]
types.untyped.Datastub has been implemented which takes the place of any non-string, non-compound, array dataset.

**Comment by ln-vidrio** [comment]
Right now, if the dataset is a H5T_String or Compound it will load the data (for some of the metadata stuff in the NWB file).  The specific requirements for what data is lazily loaded is subject to change in future commits.

**Comment by oruebel** [comment]
Thanks for the clarification. IT's great to see the lazy load for MatNWB. In terms of in-memory size, I think loading strings and compound datasets should be reasonable. The compound types might get a bit larger but right now should be Ok. For large file, loading datasets (even if they are small) may still pose a problem with regard to initial load time but will see how this goes.
