### ISSUE TITLE
Error writing processing module

### ISSUE THREAD

**Issue by sportnoah14** [NeurodataWithoutBorders/matnwb#272]
Hi,

I'm trying to include a structure in a processing module. The structure is based on a fieldtrip cfg struct that specifies parameters of an analysis. However no matter which way I do it it doesn't seem to work. Below are some examples.

```
cfg = 

  struct with fields:

               demean: 'yes'
             bsfilter: 'yes'
            bsfiltord: '3'
               bsfreq: '[59 61;119 121;179 181]'
            checkpath: 'pedantic'
    outputfilepresent: 'overwrite'
        tracktimeinfo: 'yes'
         trackmeminfo: 'yes'
               method: 'trial'
            removemcg: 'no'
            removeeog: 'no'
            precision: 'double'
              padding: '0'
               paddir: 'both'
             coordsys: 'head'
              montage: 'no'
           updatesens: 'no'
            dftfilter: 'no'
             lpfilter: 'no'
             hpfilter: 'no'
             bpfilter: 'no'
         medianfilter: 'no'
              padtype: 'data'
                reref: 'no'
            refmethod: 'avg'
             feedback: 'text'
               trials: 'all'
          polyremoval: 'no'
            polyorder: '2'
              detrend: 'no'
       baselinewindow: 'all'
           lpfilttype: 'but'
           hpfilttype: 'but'
           bpfilttype: 'but'
           bsfilttype: 'but'
            lpfiltdir: 'twopass'
            hpfiltdir: 'twopass'
            bpfiltdir: 'twopass'
            bsfiltdir: 'twopass'
     lpinstabilityfix: 'no'
     hpinstabilityfix: 'no'
     bpinstabilityfix: 'no'
     bsinstabilityfix: 'no'
        lpfiltwintype: 'hamming'
        hpfiltwintype: 'hamming'
        bpfiltwintype: 'hamming'
        bsfiltwintype: 'hamming'
         plotfiltresp: 'no'
           usefftfilt: 'no'
        medianfiltord: '9'
              dftfreq: '[50 100 150]'
              hilbert: 'no'
           derivative: 'no'
              rectify: 'no'
               boxcar: 'no'
              absdiff: 'no'
                 conv: 'no'
            dftinvert: 'no'
          standardize: 'no'

cfg_table = struct2table(avg_cfg,'AsArray',1);
cfg_table = util.table2nwb(avg_table, 'fieldtrip rereferenced cfg');

ftrip_mod = types.core.ProcessingModule('description', 'fieldtrip cfg');
ftrip_mod.dynamictable.set('fieldtrip_reref_cfg',cfg_table);
nwb.processing.set('fieldtrip_cfg', ftrip_mod);

nwbExport(nwb, f);

Error using hdf5lib2
The HDF5 library encountered an error and produced the following stack trace information:

    H5G_loc_find_cb      object 'data' doesn't exist
    H5G_traverse_real    traversal operator failed
    H5G_traverse         internal path traversal failed
    H5G_loc_find         can't find object
    H5O_open_name        object not found
    H5Oopen              unable to open object

Error in H5O.open (line 27)
output = H5ML.hdf5lib2('H5Oopen',loc_id,relname,lapl_id);

Error in io.writeAttribute (line 8)
oid = H5O.open(fid, path, 'H5P_DEFAULT');

Error in types.core.TimeSeries/export (line 208)
            io.writeAttribute(fid, [fullpath '/data/conversion'], obj.data_conversion);

Error in types.core.ElectricalSeries/export (line 87)
        refs = export@types.core.TimeSeries(obj, fid, fullpath, refs);

Error in types.untyped.Set/export (line 181)
                    refs = v.export(fid, propfp, refs);

Error in types.core.LFP/export (line 45)
            refs = obj.electricalseries.export(fid, fullpath, refs);

Error in types.untyped.Set/export (line 181)
                    refs = v.export(fid, propfp, refs);

Error in types.core.NWBFile/export (line 508)
            refs = obj.acquisition.export(fid, [fullpath '/acquisition'], refs);

Error in NwbFile/export (line 61)
                refs = export@types.core.NWBFile(obj, output_file_id, '/', {});

Error in nwbExport (line 35)
    export(nwb(i), filename);
```

I've tried this with a few different methods including creating the DynamicTable by calling `types.hdmf_common.DynamicTable`, and writing the table into another DynamicTable that is an element in each row. I'm not sure what else to try. I have another DynamicTable that is fine with writing to nwb. I'd like to store this struct so it's known what processing steps were applied to the data. Any help is greatly appreciated.

Thank you in advance,

Noah

**Comment by bendichter** [comment]
Hi @sportnoah14 

DynamicTable isn't really the best place to put something like this. This seems like the sort of thing that would be better handled with an [extension](https://pynwb.readthedocs.io/en/stable/extensions.html#extending-nwb). I can help you build this. Does this cfg struct have a consistent form in fieldtrip? Of the struct fields shown here, are any of them optional? Are there optional fields that are missing?

**Comment by sportnoah14** [comment]
Hi @bendichter , the cfg struct is output from any fieldtrip analysis. It also gives the option to add in your own fields. So there is never really consistency in the cfg struct. It's worth saving due to the level of detail it provides about the analysis. Fieldtrip output is also quite variable. If you think an extension would be the best way to handle this then I can try to create it. I can share it when I've made progress on it. Though any opinions on how to format it would be welcomed. It should definitely be a NWBDataInterface object so the processing module can store it. It could be similar to say the [LabeledEvents](https://github.com/rly/ndx-events) object but instead of discrete numeric timestamps it has a string index. I'll let you know. Thank you!

**Comment by bendichter** [comment]
If there is no consistency in the cfg struct, it's going to be difficult to create an extension. I guess I would just suggest creating a JSON and saving it as a string

**Comment by sportnoah14** [comment]
Ok that's a good idea, I'll do that. Where/how would it make sense to store a large string like that? ProcessingModule or TimeSeries description/comments?

**Comment by bendichter** [comment]
I would put it in the TimeSeries comments

**Comment by sportnoah14** [comment]
Great, thank you @bendichter. I'll close this
