### ISSUE TITLE
BehavioralSeries, BehavioralEvents and BehavioralEpochs always produce empty sets.

### ISSUE THREAD

**Issue by Xiaoyu-Tong** [NeurodataWithoutBorders/matnwb#277]
Hi,

When I tried to store behavior data into a BehavioralSeries, I found that whatever kinds of data I feed in (struct, cell array), it will not give me error, but the resultant BehavioralSeries.timeseries would always be an empty set. Therefore, I could not integrate my behavioral data to the nwb file. 

I did a little bit investigation. I checked the code for these classes. My guess is that there are two missing lines in type/core/BehavioralSeries.m, BehavioralEvents.m, and BehavioralEpochs.m:
addParameter(p, 'timeseries',[]); and obj.timeseries = p.Results.timeseries; (before and after misc.parseSkipInvalidName(p, varargin);, respectively).
However, I could not test this idea because for unknown reason, BehavioralSeries.m automatically removed my changes to restore its original version whenever I called the function types.core.BehavioralTimeSeries.

Whatever causes of the issue, can you please help me fix it so that I can integrate the behavioral data to the NWB file? Thank you!

Xiaoyu

**Comment by ln-vidrio** [comment]
Hi @Xiaoyu-Tong,

The `timeseries` property must be a `types.untyped.Set` of `types.core.TimeSeries` objects (which, I agree, should be a little clearer or should throw a warning/error). I'll take a look at improving this case. This is a requirement of the schema.

The simplest way to construct a BehavioralTimeseries without needing the Set object above is to directly provide in keyword-argument form the name of the TimeSeries object followed by the TimeSeries object. So something like:
```MATLAB
types.core.BehavioralTimeseries('ts_name', types.core.Timeseries(...));
```
will work. The TimeSeries name cannot be `timeseries`,

**Comment by Xiaoyu-Tong** [comment]
Hi @ln-vidrio ,

Thank you for the reply! Now I see how it works, but here comes the other question: is there any way in which I can directly store behavior names (such as "aggression") to TimeSeries? It seems like TimeSeries has a dtype check which prevents me doing so. The only way I figured out is to convert behavior names to numeric codes, but it would result in information difficult to understand. Thank you!

**Comment by bendichter** [comment]
@Xiaoyu-Tong could you help me understand the structure of your data? It sounds like you have behavioral states that are labeled over time, e.g. from 0s to 5 the state is "aggression" and from 5s to 10s the state is "rest". Is that right?

**Comment by Xiaoyu-Tong** [comment]
Hi, @bendichter,

Yes that is what I have for my behavioral data. Originally they are cell arrays with each element being a string (such as "aggression").

**Comment by bendichter** [comment]
Could you convert them into intervals? Then I would recommend using an IntervalSeries which would be a table with a start_time, a stop_time and custom column "label" for each interval

**Comment by Xiaoyu-Tong** [comment]
Hi @bendichter ,

Thanks for the response. Actually I tried and it seems like TimeIntervals is better fitted to this problem than IntervalSeries. However, I am having a hard time appending the TimeIntervals variable to the NWB file (as one of the acquisitions). Do you have any idea how to do that? Or it's actually IntervalSeries? But IntervalSeries does not have start_time, etc. TimeIntervals has them.

**Comment by bendichter** [comment]
@Xiaoyu-Tong 

```matlab
nwb = NwbFile( ...
    'session_description', 'mouse in open exploration',...
    'identifier', 'Mouse5_Day3', ...
    'session_start_time', datetime(2018, 4, 25, 2, 30, 3));

behavioral_states = types.core.TimeIntervals( ...
    'colnames', {'start_time', 'stop_time', 'label'}, ...
    'description', 'trial data and properties', ...
    'id', types.hdmf_common.ElementIdentifiers('data', 0:2), ...
    'start_time', types.hdmf_common.VectorData('data', [.1, 1.5, 2.5], ...
   	'description','start time of trial'), ...
    'stop_time', types.hdmf_common.VectorData('data', [1., 2., 3.], ...
   	'description','end of each trial'), ...
    'label', types.hdmf_common.VectorData( 'data', {'aggressive', 'rest', 'aggresive'}, ...
   	'description', 'whether the trial was correct'));

nwb.intervals.set('behavioral_states', behavioral_states);
```

**Comment by Xiaoyu-Tong** [comment]
Thank you so much @bendichter ! It works perfectly well. I was confusing interval and acquisition. Replacing acquisition with interval solved the problem.
