### ISSUE TITLE
opening dandiset 19

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#281]
When trying to open https://dandiarchive.org/dandiset/000019/draft

I get the following error:

```matlab
>> nwbRead('/Users/bendichter/Downloads/sub-EC2_ses-EC2-B9.nwb');
Unable to resolve the name types.core.DynamicTableRegion.

Error in io.parseDataset (line 72)
    parsed = eval([Type.typename '(kwargs{:})']);

Error in io.parseGroup (line 22)
    dataset = io.parseDataset(filename, datasetInfo, fullPath,
    Blacklist);

Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);

Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);

Error in nwbRead (line 35)
nwb = io.parseGroup(filename, h5info(filename), Blacklist);
 ```
Looking at the dataset in HDFView, the file appears to be NWB version 2.0.2:
![image](https://user-images.githubusercontent.com/844306/119580014-a323c180-bd8d-11eb-993f-bcbb39a23f67.png)

but I only see schema versions back to 2.2.0:
![image](https://user-images.githubusercontent.com/844306/119579845-4a542900-bd8d-11eb-9e60-e2a39bde97e6.png)

**Comment by ln-vidrio** [comment]
I don't see a 2.0.2 in the nwb-schema repo. Is there a particular commit in the schema that would work?

Since 2.1.0 and earlier are substantially different from 2.2.x, specific legacy support will need to be added in.

**Comment by ln-vidrio** [comment]
Oh there's a cached spec in here. This might not matter.

**Comment by ln-vidrio** [comment]
The variant EC2-B1.nwb works, testing B9

**Comment by ln-vidrio** [comment]
So this actually works if you read another file with 2.0.2 which makes me think that adding the YAML schema should fix the issue just fine. The question is where 2.0.2 actually is.

**Comment by ln-vidrio** [comment]
Does generating using #282 work for you?
