### ISSUE TITLE
char required for generating extension

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#287]
trying to generate extension https://github.com/catalystneuro/ndx-cell-explorer/tree/master/spec

```matlab
>> generateExtension("/Users/bendichter/dev/ndx-cell-explorer/spec/ndx-cell-explorer.namespace.yaml")
Check for missing argument or incorrect argument data type in
call to function 'keys'.

Error in spec.getSourceInfo (line 6)
classNames = keys(classMap);

Error in spec.generate (line 21)
    schema = spec.getSourceInfo(schemaSource);

Error in generateExtension (line 30)
    Namespace = spec.generate(namespaceText, localpath);
```

**Comment by bendichter** [comment]
This is due to using double quotes on this input instead of single quotes. We could change the `ischar()` call to `ischar() || isstring()`, which resolves this.

**Comment by bendichter** [comment]
https://github.com/NeurodataWithoutBorders/matnwb/blob/eb950b32261c459de38366381512cad098f9b9e9/%2Bspec/generate.m#L10

**Comment by ln-vidrio** [comment]
Does checking out #288 work for you?
