### ISSUE TITLE
Issue read file with nwbRead

### ISSUE THREAD

**Issue by vncntprvst** [NeurodataWithoutBorders/matnwb#292]
From the tutorial script:

read_nwbfile = nwbRead('ecephys_tutorial1.nwb')

			``Error using assert
			The condition input argument must be a scalar logical.

			Error in io.space.getReadSpace (line 13)
			assert(H5I.is_valid(sid), 'NWB:Space:GetReadSpace:InvalidId', 'Provided Space ID is invalid.');

			Error in types.untyped.DataStub/load_mat_style (line 145)
			            [readSid, memSid] = io.space.getReadSpace(shapes, sid);

			Error in types.untyped.DataStub/load (line 103)
			                data = obj.load_mat_style(varargin{1});

			Error in types.untyped.DataStub/subsref (line 303)
			                B = builtin('subsref', obj, S);

			Error in types.util.checkDtype (line 75)
			            val = val.load(1);

			Error in types.core.ElectricalSeries/validate_data (line 70)
			        val = types.util.checkDtype('data', 'numeric', val);

			Error in types.core.TimeSeries/set.data (line 100)
			        obj.data = obj.validate_data(val);

			Error in types.core.TimeSeries (line 70)
			        obj.data = p.Results.data;

			Error in types.core.ElectricalSeries (line 25)
			        obj = obj@types.core.TimeSeries(varargin{:});

			Error in io.parseGroup (line 85)
			    parsed = eval([Type.typename '(kwargs{:})']);

			Error in io.parseGroup (line 38)
			    subg = io.parseGroup(filename, group, Blacklist);

			Error in io.parseGroup (line 38)
			    subg = io.parseGroup(filename, group, Blacklist);

			Error in nwbRead (line 45)
                         nwb = io.parseGroup(filename, h5info(filename), Blacklist);``

**Comment by bendichter** [comment]
MATLAB 2020a

**Comment by bendichter** [comment]
We think we have narrowed it down.

The `assert` command works in 2020b with `assert(5)`, however in 2020a, it throws an error because the `assert` function can only take a boolean value.

**Comment by vncntprvst** [comment]
Fixed by converting `H5I.is_valid(sid)` to boolean in `+io/+space/getReadSpace.m`.
`assert(boolean(H5I.is_valid(sid)), 'NWB:Space:GetReadSpace:InvalidId', 'Provided Space ID is invalid.');`
See PR #293.

**Comment by ln-vidrio** [comment]
Apparently "boolean" worked for the pipeline even though there is no such thing in MATLAB. The command should be "logical" instead.
