### ISSUE TITLE
Bug in Matnwb: use nwb.units.getRow() to retrieve "waveforms" data

### ISSUE THREAD

**Issue by jiumao2** [NeurodataWithoutBorders/matnwb#301]
I wonder whether you have modified nwb.units.getRow() to get "waveforms" data?
I think I have set "waveforms_index" and "waveforms_index_index" right.
The "waveforms" data can't be retrieved with nwb.units.getRow(), while "spikes_time" can be retrieved normally.

This is what I have:
<img width="225" alt="1629463694(1)" src="https://user-images.githubusercontent.com/62061407/130237417-815d016e-e919-4060-9040-f50df5e9194c.png">

**Comment by oruebel** [comment]
@ln-vidrio

**Comment by bendichter** [comment]
@jjumao2 yes it's possible the `getRow` function does not work with multiple indexes. Good catch

**Comment by ln-vidrio** [comment]
How is your `colnames` property set?

**Comment by ln-vidrio** [comment]
Actually, it'd be helpful if you provided the snippet of code which populated the Unit table.

**Comment by jiumao2** [comment]
nwb.units = types.core.Units( ...
    'colnames', {'spike_times', 'waveforms', 'waveforms_index', 'waveforms_index_index', 'unit_type','cluster_id','polytrode'}, ...
    'description', ['units table, Definition for unit_type: ',r.Units.Definition{2}, ' ', r.Units.Definition{3}], ...
    'id', types.hdmf_common.ElementIdentifiers( ...
    'data', int64(0:length(spikes) - 1)), ...
    'spike_times', spike_times_vector, ...
    'spike_times_index', spike_times_index, ...
    'waveforms', waveforms_vector, ...
    'waveforms_index', waveforms_index_vector, ...
    'waveforms_index_index', waveforms_index_index_vector, ...
    'electrodes', electrode_table_region, ...
    'electrodes_index', electrode_index, ...
    'cluster_id', cluster_id, ...
    'unit_type', unit_type, ...
    'polytrode', polytrode);

waveforms_vector = 

  VectorData with properties:

    description: 'None'
           data: [64×1060195 double]

waveforms_index_vector = 

  VectorIndex with properties:

         target: [1×1 types.untyped.ObjectView]
    description: 'None'
           data: [1060195×1 uint32]

waveforms_index_index_vector = 

  VectorIndex with properties:

         target: [1×1 types.untyped.ObjectView]
    description: 'None'
           data: [16×1 uint32]

16 spikes are detected. Each spike is dectected by one channel. 
I have modified the file according to https://github.com/NeurodataWithoutBorders/matnwb/pull/302 but still met an error:

Error using mat2cell (line 89)
Input arguments, D1 through D2, must sum to each dimension of the input matrix size, [1  1].

Error in types.util.dynamictable.getRow (line 72)
        row{i} = mat2cell(row{i}, selectionLengths{iLengths});

Error in types.hdmf_common.DynamicTable/getRow (line 121)
        row = types.util.dynamictable.getRow(obj, id, varargin{:});

**Comment by jiumao2** [comment]
nwb.units = types.core.Units( ...
'colnames', {'spike_times', 'waveforms', 'waveforms_index', 'waveforms_index_index', 'unit_type','cluster_id','polytrode'}, ...
'description', ['units table, Definition for unit_type: ',r.Units.Definition{2}, ' ', r.Units.Definition{3}], ...
'id', types.hdmf_common.ElementIdentifiers( ...
'data', int64(0:length(spikes) - 1)), ...
'spike_times', spike_times_vector, ...
'spike_times_index', spike_times_index, ...
'waveforms', waveforms_vector, ...
'waveforms_index', waveforms_index_vector, ...
'waveforms_index_index', waveforms_index_index_vector, ...
'electrodes', electrode_table_region, ...
'electrodes_index', electrode_index, ...
'cluster_id', cluster_id, ...
'unit_type', unit_type, ...
'polytrode', polytrode);

waveforms_vector = 

  VectorData with properties:

    description: 'None'
           data: [67852480×1 double]
waveforms_index_vector = 

  VectorIndex with properties:

         target: [1×1 types.untyped.ObjectView]
    description: 'None'
           data: [1060195×1 uint32]
waveforms_index_index_vector = 

  VectorIndex with properties:

         target: [1×1 types.untyped.ObjectView]
    description: 'None'
           data: [16×1 uint32]
16 spikes are detected. Each spike is dectected by one channel.
I have modified the file according to #302 but it doesn't help.

>> nwb.units.getRow(1)

ans =

  1×8 table

      spike_times       spike_times_index     waveforms     waveforms_index     waveforms_index_index    unit_type    cluster_id    polytrode
    ________________    _________________    ___________    ________________    _____________________    _________    __________    _________

    {42110×1 double}          42110          {[79.7143]}    {42110×1 uint32}            42110                1            1             0

**Comment by ln-vidrio** [comment]
@jiumao2 Can you pull from that branch and try `getRow` again?

**Comment by jiumao2** [comment]
Is it related to the "colname" or dimension of "waveforms"?
The following error emerged when trying my previous dataset.

> Array indices must be positive integers or logical values.
> 
> Error in types.util.dynamictable.getRow>select (line 52)
> column = colIndStack{end};
> 
> Error in types.util.dynamictable.getRow>select (line 77)
>         selected{iSelection} = select(...
> 
> Error in types.util.dynamictable.getRow (line 44)
>     row{i} = select(DynamicTable, indexNames, ind);
> 
> Error in types.hdmf_common.DynamicTable/getRow (line 121)
>         row = types.util.dynamictable.getRow(obj, id, varargin{:});

When I tried to form new dataset with identical codes, the function "util.create_indexed_column()" didn't work. I met the following error:

> Error using types.util.correctType (line 60)
> Value must be of signage `uint`
> 
> Error in types.util.checkDtype (line 111)
>             val = types.util.correctType(val, type);
> 
> Error in types.hdmf_common.VectorIndex/validate_data (line 36)
>         val = types.util.checkDtype('data', 'uint8', val);
> 
> Error in types.hdmf_common.Data/set.data (line 31)
>         obj.data = obj.validate_data(val);
> 
> Error in types.hdmf_common.Data (line 24)
>         obj.data = p.Results.data;
> 
> Error in types.hdmf_common.VectorData (line 15)
>         obj = obj@types.hdmf_common.Data(varargin{:});
> 
> Error in types.hdmf_common.VectorIndex (line 15)
>         obj = obj@types.hdmf_common.VectorData(varargin{:});
> 
> Error in util.create_indexed_column (line 44)
> data_index = types.hdmf_common.VectorIndex( ...
> 
> Error in dataToNwb (line 334)
> [spike_times_vector, spike_times_index] = util.create_indexed_column( ...

**Comment by lawrence-mbf** [comment]
Closed as stale
