### ISSUE TITLE
Table Validators Don't Inherit Parent Columns

### ISSUE THREAD

**Issue by lawrence-mbf** [NeurodataWithoutBorders/matnwb#31]
Doesn't Break IO but will allow table columns not matching the schema.

**Comment by ehennestad** [comment]
@lawrence-mbf As this is an old issue, I first just want to check if it is still relevant, and if yes, could you provide an example illustrating the problem?

**Comment by lawrence-mbf** [comment]
@ehennestad I think this is actually indicating HDF5 compound types which I believe **can** be represented as MATLAB primitive `table` objects. I think when we used these instead of dynamic tables, this was still an issue. No idea if that is still how it is with the new schemas or not.

**Comment by ehennestad** [comment]
@oruebel Would you have any insight on this?

**Comment by oruebel** [comment]
> Would you have any insight on this?

I honestly don't know what this issue is referring to.

**Comment by ehennestad** [comment]
Closing this as it seems to be very outdated
