### ISSUE TITLE
Errror using dynamicTable.getRow when ID is 0

### ISSUE THREAD

**Issue by ryaoki** [NeurodataWithoutBorders/matnwb#310]
Hi,
When I ran this,
`row = nwb.units.getRow(0, 'useID', true, 'columns', {'spike_times'});`

I got the following error.

```
Error using types.util.dynamictable.getRow (line 13)
Expected input to be positive.

Error in types.hdmf_common.DynamicTable/getRow (line
135)
        row = types.util.dynamictable.getRow(obj, id,
        varargin{:});
```

This can be hackily solved by commenting out ln.13 in types.util.dynamictable.getRow.

**Comment by oruebel** [comment]
I believe the first parameter of ``getRow`` is the index (not the Id) of the row. Since Matlab uses 1-based indexing, I believe the correct call to retrieve the first row would be ``nwb.units.getRow(1, ...)`` instead of ``nwb.units.getRow(0, ...)``

**Comment by ryaoki** [comment]
Thank you for reply.

**Comment by ryaoki** [comment]
Thank you for reply. But I wanted to retrieve the row with ID = 0, not the first row.
I thought that if 'useID' is set to true, then first parameters is recognized as ID, not the index of the row...

**Comment by oruebel** [comment]
CC @bendichter

**Comment by ryaoki** [comment]
The issue is fixed. Thanks a lot!
