### ISSUE TITLE
Error loading some columns in dynamic table 

### ISSUE THREAD

**Issue by ryaoki** [NeurodataWithoutBorders/matnwb#312]
Hi again,

When I tried to load spike time from one of the datasets of Steinmetz et al, 2019 (https://figshare.com/articles/dataset/Datasets_from_Steinmetz_et_al_2019_in_NWB_format/11274968/1) with the following snippet,

```
%% load nwb file
nwb = nwbRead('xxxxxx\Steinmetz2019_Forssmann_2017-11-01.nwb');
nwb.units.colnames = deblank(nwb.units.colnames); % #305 
nwb.units.getRow(1, 'useID', true, 'columns', {'peak_channel'})
```
Then I got the following error

```
Error using types.untyped.DataStub/load_mat_style (line 141)
Expected input to be an array with all of the values <= 1.

Error in types.untyped.DataStub/load (line 103)
                data = obj.load_mat_style(varargin{1});

Error in types.untyped.DataStub/subsref (line 304)
                B = builtin('subsref', obj, S);

Error in types.util.dynamictable.getRow (line 56)
        row{i} = VectorData.data.load(colInd) .';

Error in types.hdmf_common.DynamicTable/getRow (line 135)
        row = types.util.dynamictable.getRow(obj, id, varargin{:});

``` 
I am not sure, but this seems to be related to the fact that ndims = 2 and dims of "peak_channel" is [1, 2073], with 1 entry in 1st dimension, because other columns (e.g. sampling_rate) with ndims = 1 can be loaded without an error.

```
 nwb.units.vectordata.get('peak_channel').data

ans = 

  DataStub with properties:

    filename: 'C:\Users\ryone\Documents\steinmetz2019\Steinmetz2019_Forssmann_2017-11-01.nwb'
        path: '/units/peak_channel'
        dims: [1 2073]
       ndims: 2

```

**Comment by bendichter** [comment]
Thanks for the report, @ryaoki. You are right that all of the other columns in that table are shape [2073] and this column is [2073 1]. That does seem to be causing the problem, but I'm not sure why. We'll look into it.

**Comment by ln-vidrio** [comment]
That is a special case which I can support. DataStub indexing doesn't quite support this case yet (1-rank indexing that overflows the first dimension of data). I'll take a look at adding that feature.

**Comment by ln-vidrio** [comment]
Take a look at #314 . Does that fix the issue?

**Comment by ryaoki** [comment]
I am sorry for late response. The issue was fixed! Thanks a lot!
