### ISSUE TITLE
Extension QoL Suggestion

### ISSUE THREAD

**Issue by owoolnough** [NeurodataWithoutBorders/matnwb#313]
One quality of life suggestion as it keeps happening to me... 
When you run nwbRead for the first time with an ECoG file it generates the +types/+ndx_ecog folder. Almost invariably I'm in another folder at the time and it generates that folder in the currently active folder. Is there any way to default it to generate into the matnwb/+types folder?

**Comment by ln-vidrio** [comment]
That was the original implementation but it was changed because not everyone prefers to write to their toolbox installation directories and it does cause a few problems if you are working with multiple different NWB schema versions at once.

I can add a workaround wherein you can provide an option in `nwbRead` to set a custom directory that the files should be saved to. Would that work? You would still have to add the generated files to path yourself I think.

**Comment by ln-vidrio** [comment]
@bendichter The default behavior currently is to save the files in the current workspace. The reasons for why it was changed from writing directly to the installation directory is mentioned above though I could simply be misremembering.

Regarding adding paths, I'd rather not change the MATLAB environment silently. To your point, saving generated files elsewhere is probably way less useful without this. Note that `addpath` paths are also automatically cleared after MATLAB restarts so even then it's not guaranteed. I believe you have to set paths explicitly in order for them to persist across MATLAB sessions.

**Comment by bendichter** [comment]
@ln-vidrio in the change you are proposing, what would the default behavior be?

**Comment by ln-vidrio** [comment]
@bendichter Same as it is now: saved in the workspace. I'm proposing adding an option to save somewhere that's not in the workspace.

**Comment by bendichter** [comment]
What if the default behavior is to save in the matnwb directory with an option to save somewhere else?

**Comment by ln-vidrio** [comment]
That would just be a reversion. Doable but it will change behavior for all users going forward again.

**Comment by ln-vidrio** [comment]
A good way to avoid the option of setting paths would be to just add an option to generate to workspace instead of the install directory.

**Comment by owoolnough** [comment]
It sounds like the best of those options would be to default into saving in the matnwb install directory with an option to save elsewhere. I imagine most data users would only have a single schema and this ensures all the required files default into the persistent MATLAB path.

**Comment by bendichter** [comment]
Yes, but I do appreciate the trade-off of not wanting to change default behavior. Inevitably this will throw off someone's workflow.
