### ISSUE TITLE
tutorial for types.hdmf_common classes

### ISSUE THREAD

**Issue by cechava** [NeurodataWithoutBorders/matnwb#318]
Need a tutorial that covers construction and usage for built-in methods that covers the following

- [x] VectorData
- [x] Vector Index
- [x] ElementIdentifier
- [x] DynamicTable
- [x] DynamicTableRegion

**Comment by bendichter** [comment]
Similar to https://hdmf.readthedocs.io/en/stable/tutorials/plot_dynamictable_tutorial.html#sphx-glr-tutorials-plot-dynamictable-tutorial-py

**Comment by bendichter** [comment]
good question, @cechava . @ln-vidrio , would it be possible to generalize DataPipe for text?

**Comment by bendichter** [comment]
@cechava is this is holding you back, let's finalize the tutorial without expandable tables and add it in later

**Comment by cechava** [comment]
not holding me back. The rest of the tutorial is ready, just need permissions to push branch to repo
