### ISSUE TITLE
UpdateThirdPartyFromUpstream.sh should be a MATLAB file

### ISSUE THREAD

**Issue by lawrence-mbf** [NeurodataWithoutBorders/matnwb#32]
For OS compatibility's sake.

**Comment by jcfr** [comment]
Since these operation are done by developer, and the script can be executed from Git bash also available on windows, I don't think this would be required.

**Comment by nclack** [comment]
@jcfr is correct, and the script is valuable as is.

However, as far as I can tell, it's not necessary to add bash as a (dev) dependency.  If someone from the community wanted to take this issue on, I'd view it as valuable.  Developers will already have matlab on their machine, and I love the idea of reducing barrier-of-entry for new devs.

I'll tag it as a low-priority enhancement.

**Comment by ehennestad** [comment]
Are there any third party dependencies in the project where this script is relevant?

**Comment by lawrence-mbf** [comment]
@ehennestad Do you mean if this script is used by anything in the repo? The answer to that is no, which is why the script hasn't been changed or this issue fixed.

**Comment by ehennestad** [comment]
So the script should be deleted and this issue closed?

**Comment by lawrence-mbf** [comment]
Yeah, at this point, I have no clue who uses this. It is usually easier to just download manually or use git.

**Comment by ehennestad** [comment]
Closing this after removing script in PR #611
