### ISSUE TITLE
Trial data support / Catch up with schema

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/matnwb#33]
The following pull requests on the nwb-schema (and PyNWB repo respectively) added new neurodata_types to the schema to improve support for trial data.

https://github.com/NeurodataWithoutBorders/pynwb/pull/536
https://github.com/NeurodataWithoutBorders/nwb-schema/pull/173

In particular the ``DynamicTable``  and ``TableColumn`` type are new. ``DynamicTable`` is essentially a column-based table consisting of an arbitrary number of ``TableColumn``.  In this way users can add arbitrary metadata columns for trial data without having to write extensions. It also adds a new group ``trials`` for storing trial data. 

There are no new features in terms of the schema-langue, i.e., these are changes to only the schema itself. It would be great if we could catch up MatNWB to the schema as the support for trial data was one of the central needs identified during the hackathons. 

@nclack @ln-vidrio

**Comment by bendichter** [comment]
@ln-vidrio close?
