### ISSUE TITLE
int type error

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#339]
It looks like `int`s are being saved in the wrong byte size. The following should produce int16s but it produces int8s.

```matlab
spikes = {[1., 2., 3.], [2., 3., 4., 5.]};

[spike_times_vector, spike_times_index] = util.create_indexed_column(spikes);

nwb = NwbFile( ...
    'session_description', 'mouse in open exploration',...
    'identifier', 'Mouse5_Day3', ...
    'session_start_time', datetime(2018, 4, 25, 2, 30, 3) ...
);

nwb.units = types.core.Units( ...
    'colnames', {'spike_times'}, ...
    'description', 'units table', ...
    'id', types.hdmf_common.ElementIdentifiers( ...
        'data', int16(0:length(spikes) - 1) ...
    ), ...
    'spike_times', spike_times_vector, ...
    'spike_times_index', spike_times_index ...
);

nwbExport(nwb, 'colnames_demo.nwb')
```

![image](https://user-images.githubusercontent.com/844306/141326010-cb674839-650b-4081-aa18-3bfd0ae080d1.png)

@ln-vidrio any ideas here would be greatly appreciated.

**Comment by emilyasterjones** [comment]
All `int` variables that are passed through `types.util.correctType` are getting cast down to the smallest possible int size. Starting at line 67:
```
intSizeScale = [8 16 32 64];
for iSize = find(minSize == intSizeScale, 1):find(classSize == intSizeScale, 1)
    sizeType = sprintf('%s%d', prefix, intSizeScale(iSize));
    if all(minVal >= double(intmin(sizeType))) && all(maxVal <= double(intmax(sizeType)))
        val = cast(val, sizeType);
        break;
    end
end
```
So all the `ElementIdentifier` ids are getting cast to `int8`.

For now, I'm patching my local copy by replacing that block with:
```
sizeType = sprintf('%s%d', prefix, 32);
val = cast(val, sizeType);
```

However, it appears that something in `nwbExport` is also casting these ints. The NWB object I'm working with now has ElementIdentifier ids that are `int32`, but when I export it, HDFViewer shows they are still `int8`. I'll keep looking.

**Comment by cechava** [comment]
a more general solution is to modify `checkDtype` to recognize when `val` is not a double. In that case, the user has cast the array to a specific type and we should not attempt to correct the type.  I will start a PR with this modification.
