### ISSUE TITLE
Cannot load in nwb file

### ISSUE THREAD

**Issue by tekriwal** [NeurodataWithoutBorders/matnwb#343]
>> nwb_pdil = nwbRead(fullfile('/Users','andytekriwal','Box','EMU','STUDY_PDIL',ptPlaceholder, 'SEEG', 'processed', ephysfilename));
Index exceeds the number of array elements (0).

Error in types.util.correctType (line 57)
prefix = typeMatch{1};

Error in types.core.AnnotationSeries (line 10)
        varargin = [{'comments' 'no comments' 'data_conversion' types.util.correctType(1, 'float32')
        'data_resolution' types.util.correctType(-1, 'float') 'data_unit' 'n/a' 'description' 'no description'}
        varargin];

Error in io.parseGroup (line 85)
    parsed = eval([Type.typename '(kwargs{:})']);

Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);

Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);

Error in nwbRead (line 45)
nwb = io.parseGroup(filename, h5info(filename), Blacklist);

%%%%%%%%%

%as requested, see below for output from schema check
util.getSchemaVersion(fullfile('/Users','andytekriwal','Box','EMU','STUDY_PDIL',ptPlaceholder, 'SEEG', 'processed', ephysfilename))
ans = '2.1.0'

**Comment by ln-vidrio** [comment]
Ah, part of this is that schema version `2.1.0` is not present as a schema option. The other is actually a bug in the dtype not supported `float` types as it should. I will follow up this ticket with updates for the two issues.

**Comment by ln-vidrio** [comment]
#344 has added 2.1.0 as a valid schema which has now been merged so re-downloading from the Github repository should . Working on the `float` discrepancy.

**Comment by tekriwal** [comment]
Great, trying it now!

Best,
Andy Tekriwal
609-276-1076

**Comment by ln-vidrio** [comment]
Ah, sorry. You will most likely receive the same error because the `float` discrepancy is the error message we're seeing in the ticket.

**Comment by tekriwal** [comment]
Yeah, still getting error. Wasn't sure if I was doing something wrong on my
end though so thanks for letting me know. Is there anything I can do on my
end to help or wait to hear back when a change is pushed?

Best,
Andy Tekriwal
609-276-1076

**Comment by ln-vidrio** [comment]
I'm currently waiting on #345 's tests to finish. Once that finishes I can let you know that you can test it.

**Comment by tekriwal** [comment]
Thank you!

Best,
Andy Tekriwal
609-276-1076

**Comment by ln-vidrio** [comment]
That is done, when you find the time let me know if the new main branch works.

**Comment by tekriwal** [comment]
Cool! I am good to go, thank you.

Should I mark the issue resolved or something on me end?

Best,
Andy Tekriwal
609-276-1076

**Comment by ln-vidrio** [comment]
I can do that.
