### ISSUE TITLE
better shape constraint error message

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#370]
see https://github.com/NeurodataWithoutBorders/helpdesk/discussions/16

**Comment by ln-vidrio** [comment]
Wouldn't this be a request for better shape validation in MatNWB? The error in the ticket looks like it comes from a pynwb validation. Was there a MatNWB when exporting the file from MATLAB?

**Comment by ln-vidrio** [comment]
Sorry,
> Was there a MatNWB **error** when exporting the file from MATLAB?

**Comment by bendichter** [comment]
oh yes, you are right. Do we do shape checking in MatNWB?

**Comment by ln-vidrio** [comment]
I thought we did but I'm betting it's much more loose than the validators.

**Comment by ln-vidrio** [comment]
I'll take a look

**Comment by ln-vidrio** [comment]
We do but it appears to be too loose.
