### ISSUE TITLE
Tutorial typo

### ISSUE THREAD

**Issue by ehennestad** [NeurodataWithoutBorders/matnwb#393]
From the matlab tutorial for calcium imaging:
https://neurodatawithoutborders.github.io/matnwb/tutorials/html/ophys.html

read_nwbfile.processing.get('behavior').nwbdatainterface.get('Position').spatialseries.get('SpatialSeries')

should be 
read_nwbfile.get('processing').etc

**Comment by ln-vidrio** [comment]
@ehennestad That's odd, read_nwbfile should be a NwbFile object and `processing` is listed as a property for me. Can you post what `read_nwbfile` looks like for you?

**Comment by ehennestad** [comment]
It might be that the file I was trying to read was an old version. I updated my local matnwb repository, and now I can not open the file any longer.
