### ISSUE TITLE
Namespace label inconsistency

### ISSUE THREAD

**Issue by mpompolas** [NeurodataWithoutBorders/matnwb#398]
I am using the latest NWB version and trying to load some files I created last year.

I get this error during reading the NWB file:
```
Error using save
The argument to -STRUCT must be the name of a scalar structure variable.

Error in spec.saveCache (line 10)
save(cachePath, '-struct', 'NamespaceInfo');
```

The problem is due to inconsistencies ('-', '_') in the Namespace on this line in `nwbRead`:
`Namespace = Namespaces(strcmp({Namespaces.name}, namespaceName));
`
that returns an empty Namespace, since:

```
Namespaces = 

  struct with fields:

            name: 'hdmf-common'
       filenames: {'table'  'sparse'}
    dependencies: {1×0 cell}
         version: '1.1.3'
       namespace: [1×1 containers.Map]
          schema: [2×1 containers.Map]

```

```
namespaceName =

    'hdmf_common'
```

**Comment by ln-vidrio** [comment]
We reverted that change a while ago but I'll add legacy support for underscores such as this. Thanks for reporting the issue!
