### ISSUE TITLE
Fix .gitignore to allow new `+types/+untyped` and `+types/+util` functions

### ISSUE THREAD

**Issue by lawrence-mbf** [NeurodataWithoutBorders/matnwb#414]
We currently use the negation operator to negate all generated class files from being added to the repository. Unfortunately, due to a quirk in git, this negation doesn't completely work when adding new files even in "negated" directories:
https://www.atlassian.com/git/tutorials/saving-changes/gitignore

The best solution right now is to add common `gitignore` records for `core`, `hdmf-common`, and `hdmf-experimental` and practice due diligence in removing extension schemas in subsequent PRs.

**Comment by lawrence-mbf** [comment]
One other workaround is for developers to remember to use `git add -f` when adding new files.

**Comment by ehennestad** [comment]
Closing this as it is not relevant after PR #556
