### ISSUE TITLE
[Feature]: Allow `toTable()` on extension subtypes of `DynamicTable`

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/matnwb#418]
### What would you like to see added to MatNWB?

I have an NWB extension that includes a type that extends `DynamicTable`. I want to be able to visualize this table in MatNWB.

For example, in the [ndx-events extension](https://github.com/rly/ndx-events), `AnnotatedEventsTable` extends `DynamicTable`. However the following code does not work:

```matlab
>> annotated_events = types.ndx_events.AnnotatedEventsTable()

annotated_events = 

  AnnotatedEventsTable with properties:

    event_description: []
          event_times: []
    event_times_index: []
                label: []
             colnames: []
          description: []
                   id: []
           vectordata: [0×1 types.untyped.Set]

>> annotated_events.toTable()
Unrecognized method, property, or field 'toTable' for class 'types.ndx_events.AnnotatedEventsTable'.
``` 

### What solution would you like?

Add support for `toTable()` to extension types that extend `DynamicTable`.

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/matnwb/blob/improved_issue_templates/.github/CODE_OF_CONDUCT.md)
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

**Comment by rly** [comment]
Actually, does the `toTable()` method referenced in the [DynamicTable tutorial](https://neurodatawithoutborders.github.io/matnwb/tutorials/html/dynamic_tables.html) still work for DynamicTable objects? 

```matlab
>> my_table = types.hdmf_common.[DynamicTable](matlab:helpPopup types.hdmf_common.DynamicTable)()

my_table = 

  DynamicTable with properties:

       colnames: []
    description: []
             id: []
     vectordata: [0×1 types.untyped.Set]

>> my_table.toTable()
Unrecognized method, property, or field 'toTable' for class 'types.hdmf_common.DynamicTable'.
```

**Comment by lawrence-mbf** [comment]
That's interesting, the file generation does have a `toTable` method in version `2.4.0` and in master. Which MatNWB version is this?

**Comment by lawrence-mbf** [comment]
Testing out your code with `ndx-events`: the `toTable` method is included in the AnnotatedEventsTable but I do see an error when the table is empty:
```
Dot indexing is not supported for variables of this type.

Error in types.util.dynamictable.nwbToTable (line 35)
if isa(DynamicTable.id.data, 'types.untyped.DataStub')...

Error in types.hdmf_common.DynamicTable/toTable (line 123)
        table = types.util.dynamictable.nwbToTable(obj, varargin{:});
```

I'll open a PR fix for that. Can you try this on your machine using the tip of `master`?

**Comment by lawrence-mbf** [comment]
Can confirm that the provided code works in the newest release. If there are further issues, make a new ticket.

**Comment by lawrence-mbf** [comment]
Can confirm that the provided code works in the newest release. If there are further issues, make a new ticket.
