### ISSUE TITLE
error reading NWB file with cached spec

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#42]
There's a new feature in pynwb that caches the specs used to generate the file within the file itself. Here's an example:

```python
from pynwb import NWBFile, NWBHDF5IO
from datetime import datetime

nwbfile = NWBFile('source', ' ', ' ',
                  datetime.now(), datetime.now(),
                  institution='University of California, San Francisco',
                  lab='Chang Lab')

with NWBHDF5IO('test_cache.nwb', 'w') as io:
    io.write(nwbfile, cache_spec=True)
```
[Here](https://www.dropbox.com/s/nlqjxpxoho1kje7/test333.nwb?dl=1) is the produced file. 

If only the core is used it caches the text of `core.namespace.yaml`. If extensions are used, it also stores those. This allows users to automatically load data even if the data is defined by an external spec and allows the extensions so be passed with the data without worrying about versions of extensions, etc.

Would it be possible to read these specs and automatically generate the defined classes?

Here's an example with an extension:
```python
from pynwb.spec import NWBDatasetSpec, NWBNamespaceBuilder, NWBGroupSpec

name = 'test'
ns_path = name + '.namespace.yaml'
ext_source = name + '.extensions.yaml'

test_obj = NWBGroupSpec(
    neurodata_type_def='TestObj',
    doc='test object',
    datasets=[NWBDatasetSpec(name='filler_data', doc='data doc', dtype='int',
                             shape=(None, 1))],
    neurodata_type_inc='NWBDataInterface')

ns_builder = NWBNamespaceBuilder(name + ' extensions', name)
ns_builder.add_spec(ext_source, test_obj)
ns_builder.export(ns_path)



from datetime import datetime

from pynwb import load_namespaces, register_class, NWBFile, NWBHDF5IO
from pynwb.core import NWBDataInterface
from pynwb.form.utils import docval, popargs
from collections import Iterable


# load custom classes
load_namespaces(ns_path)


@register_class('TestObj', 'test')
class TestObj(NWBDataInterface):
    __nwbfields__ = ('filler_data',)

    @docval({'name': 'name', 'type': str, 'doc': 'name'},
            {'name': 'source', 'type': str, 'doc': 'source?'},
            {'name': 'filler_data', 'type': Iterable, 'doc': 'data'})
    def __init__(self, **kwargs):
        name, source, filler_data = popargs('name', 'source', 'filler_data',
                                            kwargs)
        super(TestObj, self).__init__(name, source, **kwargs)
        self.filler_data = filler_data


nwbfile = NWBFile(source='0',
                  session_description='0',
                  identifier='0',
                  session_start_time=datetime(1900, 1, 1))

nwbfile.add_acquisition(TestObj(name='name', source='source', filler_data=[1]))

with NWBHDF5IO('test_extension.nwb', 'w') as io:
    io.write(nwbfile, cache_spec=True)
```

[Here](https://www.dropbox.com/s/i7mx8gvumnlh5ea/test_extension.nwb?dl=1) is the generated file.

**Comment by bendichter** [comment]
@ln-vidrio should I take a crack at this?

**Comment by ln-vidrio** [comment]
We don't do much with cached spec at this point but the main issue looks to be that pynwb embeds hidden attributes like `.specloc` which break MATLAB's `inputParser`.  Considering that these are not in the spec at all, it might be easiest to drop these values from class instantiation and maybe store them elsewhere for later use.

I can see why they'd use this for caches though, it's a bit of a chicken/egg problem.

**Comment by bendichter** [comment]
sounds good. After talking with the dev team, I don't know if this feature is going to last, so I'm going to focus on reading external extensions.
