### ISSUE TITLE
[Feature]: Use branch protections to avoid commits to the main branch

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/matnwb#426]
### What would you like to see added to MatNWB?

I noticed that the main branch currently does not have any protections set up. We should setup branch protections here
https://github.com/NeurodataWithoutBorders/matnwb/settings/branches to make sure that changes to master are only permitted via PRs. We are using the same practice of permitting commits to the main branch only via PRs also for most other NWB repos. I'm happy to help with those changes, but I didn't want to cause any trouble in development by changing repo settings without checking here first. 

### Is your feature request related to a problem?

I was able to accidentally commit the changes I proposed in https://github.com/NeurodataWithoutBorders/matnwb/pull/425 directly to master. I reverted those changes, but ideally we should not permit commits directly to master to ensure that all changes are reviewed in PRs/ 

### What solution would you like?

Add branch protections via https://github.com/NeurodataWithoutBorders/matnwb/settings/branches

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/matnwb/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

**Comment by lawrence-mbf** [comment]
`master` Branch protections are now set for everyone, including administrators.
