### ISSUE TITLE
[Bug]: checkConfig for dynamictable does not work for AlignedDynamicTable object

### ISSUE THREAD

**Issue by mfeyerab** [NeurodataWithoutBorders/matnwb#434]
### What happened?

I am still struggling creating MATNWB objects for intracellular electrophysiology. The issue is similar to my previous bug report https://github.com/NeurodataWithoutBorders/matnwb/issues/432, in which the detected table height is incorrect and fails to be the same as the number of rows. This time it is the types.core.IntracellularRecordingsTable object. However, I believe it is easier to demonstrate the bug with the more abstract parent class types.hdmf_common.AlignedDynamicTable. It is suppose to have the same number of rows as the dynamic tables it contains, but it fails the config check that way. The minimal example is based on code from the dynamic table tutorial, execpt the creation of the AlignedDynamicTable

 

### Steps to Reproduce

```matlab
col1 = types.hdmf_common.VectorData( ...
    'description', 'column #1', ...
    'data', [1;2] ...
);
col2 = types.hdmf_common.VectorData( ...
    'description', 'column #2', ...
    'data', {'a';'b'} ...
);

my_table = types.hdmf_common.DynamicTable( ...
    'description', 'an example table', ...
    'colnames', {'col1', 'col2'}, ...
    'col1', col1, ...
    'col2', col2, ...
    'id', types.hdmf_common.ElementIdentifiers('data', [0;1]) ...  
);

my_2nd_table = types.hdmf_common.DynamicTable( ...
    'description', 'an example table', ...
    'colnames', {'col1', 'col2'}, ...
    'col1', col1, ...
    'col2', col2, ...
    'id', types.hdmf_common.ElementIdentifiers('data', [0;1]) ...  
);

types.hdmf_common.AlignedDynamicTable(...
   'categories', {'T1' ,'T2'},...
   'colnames', {'tables'},...
  'T1',my_table ,...
  'T2', my_2nd_table,...
    'description', '', ...
    'id', types.hdmf_common.ElementIdentifiers('data', [0;1]) ...
)
```

### Error Message

```matlab
Error using types.util.dynamictable.checkConfig (line 60)
Special column `id` of DynamicTable needs to match the detected height of 0. Found 2 IDs.
Error in types.hdmf_common.AlignedDynamicTable (line 32)
            types.util.dynamictable.checkConfig(obj);
Error in minimal (line 26)
types.hdmf_common.AlignedDynamicTable(...
```

### Operating System

Windows

### Matlab Version

'9.9.0.1495850 (R2020b) Update 1'

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/matnwb/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

**Comment by lawrence-mbf** [comment]
AlignedTables looks interesting but replacing the `colnames` argument with an empty cell array appears to resolve this issue. Is there a reason for that column name? The reason for the error is because the configuration is looking for a VectorData column called `tables` which should be set as another argument and should be of height 2.

@bendichter if you have more input on how this type is usually used, that would be good to know as well.

**Comment by mfeyerab** [comment]
I noticed that I made 2 little mistakes in the code (which I updated in the previous post)  and made sure that my script runs with the current master-branch with schema 2.4.0. (I checked in the nwb_version of the nwb object) Now my error messages look like this:

        Error using hdf5lib2
        The HDF5 library encountered an unknown error.
        Error in H5A.write (line 53)
        H5ML.hdf5lib2('H5Awrite', attr_id, type_id, buf);
        Error in io.writeAttribute (line 25)
        H5A.write(id, tid, data);
        Error in types.hdmf_common.DynamicTable/export (line 102)
                io.writeAttribute(fid, [fullpath '/colnames'], obj.colnames, 'forceArray');
        Error in types.hdmf_common.AlignedDynamicTable/export (line 68)
                refs = export@types.hdmf_common.DynamicTable(obj, fid, fullpath, refs);
        Error in types.core.IntracellularRecordingsTable/export (line 60)
                refs = export@types.hdmf_common.AlignedDynamicTable(obj, fid, fullpath, refs);
        Error in types.core.NWBFile/export (line 904)
                    refs = obj.general_intracellular_ephys_intracellular_recordings.export(fid, [fullpath 
               '/general/intracellular_ephys/intracellular_recordings'], refs);
        Error in NwbFile/export (line 62)
                        refs = export@types.core.NWBFile(obj, output_file_id, '/', {});
        Error in nwbExport (line 36)
            nwb(i).export(filename);
        Error in minimal2 (line 103)
                nwbExport(nwbfile, 'test_new_icephys.nwb');

**Comment by mfeyerab** [comment]
Hello,

I am just wondering if there is any news? I tried recently with the newest release, but could not make it work either. I am unable to use releases past 2.4.0.0 because I cannot create an IntracellularRecordingsTable object that passes checkConfig for dynamictables. Am I the only ICEphys guy who is struggling with this? Is there a workaround?

**Comment by lawrence-mbf** [comment]
I apologize @mfeyerab this must have fallen through. I'll see if I can get the branch in #436 merged in and get your stuff tested.

**Comment by lawrence-mbf** [comment]
On the off-chance, could you run your test code with #436 if you can and let me know if that fixes the issue? I'd first like to see where I left off.

**Comment by mfeyerab** [comment]
I tested it. The edits from #436 seem to get rid of the issue. Thanks for the fast response!

**Comment by lawrence-mbf** [comment]
Hi @mfeyerab can you confirm that the tip of `master` is now working for you?

**Comment by mfeyerab** [comment]
@lawrence-mbf It is working for me now. Thanks again!

**Comment by lawrence-mbf** [comment]
Awesome, closing this issue now.
