### ISSUE TITLE
[Bug]: Syntax valid only after Matlab 2018b

### ISSUE THREAD

**Issue by ftadel** [NeurodataWithoutBorders/matnwb#437]
### What happened?

The syntax `maxVal = max(val, [], 'all');` is used here:
https://github.com/NeurodataWithoutBorders/matnwb/blob/master/%2Btypes/%2Butil/correctType.m#L34

It appeared in Matlab 2018b and crashes before that.
But it seems like matnwb should be working with older versions of Matlab.

This newer syntax can be easily replaced with: 
`maxVal = max(val(:));`

This error was reported on the Brainstorm forum:
https://neuroimage.usc.edu/forums/t/error-opening-nwb-files/21025/20

### Steps to Reproduce

```matlab
Using Matlab 2017b
```

### Error Message

```matlab
** Error: Line 34: max
** Invalid option. Option must be 'omitnan' or 'includenan'.
**
** Call stack:
** >correctType.m at 34
** >checkDtype.m at 111
** >DynamicTableRegion.m>DynamicTableRegion.validate_data at 34
** >Data.m>Data.set.data at 29
** >Data.m>Data.Data at 22
** >VectorData.m>VectorData.VectorData at 13
** >DynamicTableRegion.m>DynamicTableRegion.DynamicTableRegion at 13
** >parseDataset.m at 72
** >parseGroup.m at 22
** >parseGroup.m at 38
** >parseGroup.m at 38
** >nwbRead.m at 59
```

### Operating System

Windows

### Matlab Version

2017b

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/matnwb/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

**Comment by bendichter** [comment]
Thanks for raising this @ftadel. It's good to have documentation of this issue in case others run into it. Thanks for the fix suggestion. I think in this particular case we might be able to just use the more generic syntax you suggest for compatibility.

This does raise a bigger question though of what versions of MATLAB we want to support in cases where the changes would need to be more substantial. I think going more than 5 years back might be difficult. Certainly certain features such as dynamically loaded filters would not be available. I was under the impression that most MATLAB users have a license that entitles them to download the latest version, so I am surprised to see such an old version being actively used. @lawrence-mbf, what do you think? Do you have a sense of what versions of MATLAB our users are using and how difficult it would be to support the tail of that distribution?

**Comment by lawrence-mbf** [comment]
For ScanImage right now we just bumped it up to 2018a. My assumption was the same as yours that most universities have a site-wide license which allows them access to the newest release.

**Comment by ftadel** [comment]
> My assumption was the same as yours that most universities have a site-wide license which allows them access to the newest release.

Unfortunately, this is true in rich universities of rich countries only.
On the Brainstorm forum, we commonly address requests from users with Matlab license older than 5yrs.

When it does not require much extra work (like in the example above with `max`), we try to always favor the most backward-compatible syntax. 
Similarly, for all the functions from specialized commercial toolboxes, we try to provide alternatives using only the basic install of Matlab (e.g. `hilbert.m` from the Signal Processing toolbox replaced with an alternative adapted from Octave).

**Comment by lawrence-mbf** [comment]
That's good to know. I guess for now we'll try and limit ourselves to 2017a and if there is a need to go older we can address that specifically.
