### ISSUE TITLE
getting linked data

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#45]
I'm trying to access linked data, e.g. `lfp.electrodes.data`

which gives:
```
  RegionView with properties:

       path: '/general/extracellular_ephys/electrodes'
       view: [1×1 types.untyped.ObjectView]
     region: {[1 338]}
       type: 'H5T_STD_REF_DSETREG'
    reftype: 'H5R_DATASET_REGION'
```

but I don't see any methods to actually follow that link to the data. Is there a convenient way to do this?

**Comment by bendichter** [comment]
it appears that this is supported but undocumented. I'll add some comments to clarify this for future users

**Comment by ln-vidrio** [comment]
Given a nwb object as argument, the refresh() method should load the referenced region.  If it's a datastub, it should be able to reference the proper region.
You'll find it at `types.untyped.RegionView` (Line 31)

**Comment by bendichter** [comment]
ah ok I'll add some comments to make that more clear
