### ISSUE TITLE
[Bug]: Cannot load NWB file generated using Python

### ISSUE THREAD

**Issue by dervinism** [NeurodataWithoutBorders/matnwb#453]
### What happened?

The issue has originally been reported [here](https://github.com/AllenInstitute/AllenSDK/issues/2513#issuecomment-1208227325).

### Steps to Reproduce

```matlab
Refer to the allensdk issue
```

### Error Message

```matlab
Refer to the allensdk issue
```

### Operating System

Windows

### Matlab Version

R2021a

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/matnwb/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

**Comment by lawrence-mbf** [comment]
Hi @dervinism apologies for the late reply, could you use the tip of MatNWB master and see if reading still causes that issue?

**Comment by ehennestad** [comment]
`nwbRead(~/ecephys_session_766640955.nwb)` works on the current version of matnwb (bc4b87dc2de6f1c2b7955d9db62d7143d83ae485)
