### ISSUE TITLE
[Bug]: VectorData.data is converted to string: Error using hdf5lib2 The memory type is incompatible with H5T_STRING.

### ISSUE THREAD

**Issue by dervinism** [NeurodataWithoutBorders/matnwb#462]
### What happened?

In some instances VectorData property data is being converted to an array of strings upon saving the NWB file. When the conversion fails, the error is issued:
```
Error using hdf5lib2
The memory type is incompatible with H5T_STRING.  Consider using
'H5ML_DEFAULT' instead.
```
If I manually convert data into an array of strings, the issue is resolved. However, I don't understand why in some instances I can use an array of numbers and in other instances I have convert them to strings. The documentation states that data property can be any type. This occurs when I try to construct the units table.

### Steps to Reproduce

```matlab
nwb.units = types.core.Units( ...
    'colnames', {'cluster_id','local_cluster_id','type',...
    'peak_channel_index','peak_channel_id',... % Provide the column order. All column names have to be defined below
    'local_peak_channel_id','rel_horz_pos','rel_vert_pos',...
    'isi_violations','isolation_distance','area','probe_id',...
    'spike_times','spike_times_index'}, ...
    'description', 'Units table', ...
    'id', types.hdmf_common.ElementIdentifiers( ...
    'data', int64(0:length(spikes) - 1)), ...
    'cluster_id', types.hdmf_common.VectorData( ...
    'data', metadata(:,1), ...
    'description', 'Unique cluster id'), ...
    'local_cluster_id', types.hdmf_common.VectorData( ...
    'data', metadata(:,2), ...
    'description', 'Local cluster id on the probe'), ...
    'type', types.hdmf_common.VectorData( ...
    'data', metadata(:,3), ...
    'description', 'Cluster type: unit vs mua'), ...
    'peak_channel_index', types.hdmf_common.VectorData( ...
    'data', metadata(:,4), ...
    'description', 'Peak channel row index in the electrode table'), ...
    'peak_channel_id', types.hdmf_common.VectorData( ...
    'data', metadata(:,5), ...
    'description', 'Unique ID of the channel with the largest cluster waveform amplitude'), ...
    'local_peak_channel_id', types.hdmf_common.VectorData( ...
    'data', metadata(:,6), ...
    'description', 'Local probe channel with the largest cluster waveform amplitude'), ...
    'rel_horz_pos', types.hdmf_common.VectorData( ...
    'data', metadata(:,7), ...
    'description', 'Probe-relative horizontal position in mm'), ...
    'rel_vert_pos', types.hdmf_common.VectorData( ...
    'data', metadata(:,8), ...
    'description', 'Probe tip-relative vertical position in mm'), ...
    'isi_violations', types.hdmf_common.VectorData( ...
    'data', metadata(:,9), ...
    'description', 'Interstimulus interval violations (unit quality measure)'), ...
    'isolation_distance', types.hdmf_common.VectorData( ...
    'data', metadata(:,10), ...
    'description', 'Cluster isolation distance (unit quality measure)'), ...
    'area', types.hdmf_common.VectorData( ...
    'data', metadata(:,11), ...
    'description', ['Brain area where the unit is located. Internal thalamic' ...
    'nuclei divisions are not precise, because they are derived from unit locations on the probe.']), ...
    'probe_id', types.hdmf_common.VectorData( ...
    'data', metadata(:,12), ...
    'description', 'Probe id where the unit is located'), ...
    'spike_times', spike_times_vector, ...
    'spike_times_index', spike_times_index, ...
    'electrode_group', types.hdmf_common.VectorData( ...
    'data', metadata(:,13), ...
    'description', 'Recording channel groups'), ...
    'electrodes', types.hdmf_common.DynamicTableRegion('table', ...
    types.untyped.ObjectView('/general/extracellular_ephys/electrodes'), ...
    'description',  'Probe recording channels', ...
    'data', cell2mat(table2array(metadata(:,1)))), ...
    'waveform_mean', types.hdmf_common.VectorData( ...
    'data', waveformMeans, ...
    'description', ['Mean waveforms on the probe channel with the largest waveform amplitude.' ...
    'MUA waveforms are excluded. The order that waveforms are stored match the order of units in the unit table.']) ...
    );

These lines cause the error:
    'rel_horz_pos', types.hdmf_common.VectorData( ...
    'data', metadata(:,7), ...
    'description', 'Probe-relative horizontal position in mm'), ...
    'rel_vert_pos', types.hdmf_common.VectorData( ...
    'data', metadata(:,8), ...
    'description', 'Probe tip-relative vertical position in mm'), ...

If I convert every element of metadata(:,7) and metadata(:,8) to strings, then error is resolved. Using any other data type causes the error.
```

### Error Message

```matlab
Error using hdf5lib2
The memory type is incompatible with H5T_STRING.  Consider using
'H5ML_DEFAULT' instead.

Error in H5D.write (line 100)
H5ML.hdf5lib2('H5Dwrite', varargin{:});

Error in io.writeCompound (line 110)
H5D.write(did, tid, sid, sid, 'H5P_DEFAULT', data);

Error in types.untyped.MetaClass/write_base (line 24)
                    io.writeCompound(fid, fullpath, obj.data);

Error in types.untyped.MetaClass/export (line 66)
            refs = obj.write_base(fid, fullpath, refs);

Error in types.hdmf_common.Data/export (line 37)
        refs = export@types.untyped.MetaClass(obj, fid, fullpath, refs);

Error in types.hdmf_common.VectorData/export (line 55)
        refs = export@types.hdmf_common.Data(obj, fid, fullpath, refs);

Error in types.untyped.Set/export (line 181)
                    refs = v.export(fid, propfp, refs);

Error in types.hdmf_common.DynamicTable/export (line 106)
            refs = obj.vectordata.export(fid, fullpath, refs);

Error in types.core.Units/export (line 140)
        refs = export@types.hdmf_common.DynamicTable(obj, fid, fullpath,
        refs);

Error in types.core.NWBFile/export (line 1078)
            refs = obj.units.export(fid, [fullpath '/units'], refs);

Error in NwbFile/export (line 62)
                refs = export@types.core.NWBFile(obj, output_file_id, '/',
                {});

Error in nwbExport (line 36)
    nwb(i).export(filename);

Error in convert2nwb (line 260)
    nwbExport(nwb, [animalDerivedDataFolderNWB filesep 'ecephys_session_0'
    num2str(iSess) '.nwb']);
```

### Operating System

Windows

### Matlab Version

R2021a

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/matnwb/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

**Comment by dervinism** [comment]
Hi Lawrence,

metadata is a Matlab table but individual values are double. Other table columns contain either doubles or strings. If I input any other table columns with doubles, they produce the same error. The only things that works is converting doubles into strings. However, no such issue for other entries excepts for waveform_mean which has the same issue.

**Comment by lawrence-mbf** [comment]
Are you using any extension schemas? Specifically anything that might overload the Units table declaration? I'm not seeing anything special with `rel_vert_pos` and `rel_horz_pos` using the normal schema.

**Comment by dervinism** [comment]
No extensions. ```rel_vert_pos``` and ```rel_horz_pos``` are just like other entries. Nothing special about them.

**Comment by lawrence-mbf** [comment]
So when you index into a table using parentheses, you actually get another table containing only that column. When exporting, this is actually presumed to be a compound type and we encode all the types that way. I'm not sure why `table2struct` converted your values to struct but this might be a problem.

I understand this might be asking a lot but could you try this script but replacing the table indexing instances `metadata(:,1)` with curly braces instead of round ones (i.e. `metadata{:,1}`)?

**Comment by dervinism** [comment]
metadata{:,1} gives a column cell array of doubles. The NWB file is saved fine, but the saved values are random strings. Presumably the numbers are translated into strings.

cell2mat(metadata{:,1}) gives a column vector of doubles. It crashes the code with the typical error.

**Comment by lawrence-mbf** [comment]
I am unable to recreate this issue on my end using random double values. Is it possible for you to send a subset of the non-working NWB file? I can send you a link where you can upload it.

**Comment by lawrence-mbf** [comment]
Oh, nevermind. I missed your reference to your cell array of doubles.

Blocking primitive cell arrays is currently not supported through regular construction (it *is* supported in `addRow` syntax). Were you trying to create ragged arrays using this format?

**Comment by dervinism** [comment]
I am not sure I understand your reply. As I said, the error is caused by all data types except strings. I can share the code with the data example that reproduces the error.

**Comment by lawrence-mbf** [comment]
At the current moment and from what I could glean from your comments, what you're trying to do won't work without script modification. There's no support for storing cell arrays of doubles and MatNWB assumes that cell arrays are strings (which should now throw an error as of the tip of master).

Is this part of a downstream automation that was read in from another NWB file by chance? Otherwise I'm not sure why you have cell arrays of doubles from indexing into your table.

**Comment by dervinism** [comment]
I don't have cell arrays. I have a Matlab table. Indexing into a table will give cell arrays. But you can convert them to any type of data. Whatever type is used, either the error is thrown or data is converted to strings amd the output no longer makes sense.

**Comment by lawrence-mbf** [comment]
Right, the tip of master should now throw an error when it encounters a cell array of doubles as that is not representable in HDF5 on its own.

In the case of MATLAB tables, grouping doubles into vectors of cell arrays is to allow for a variable number of double values per row. Do you happen to know if that is the case here or is it just preventative? If so, then you will need to use a different method to construct your dynamic table (something like `util.table2nwb` or `addRow`).

**Comment by dervinism** [comment]
I don't know the answer to your question. I'll try out the latest matnwb and see if I still get the error.

**Comment by lawrence-mbf** [comment]
I'll follow up tomorrow but my recommendation is to use the `dynamictable = util.table2nwb(metadata, 'description');` function provided as that should get you most of the way there with the proper nwb object structure.

Sep 6, 2022 17:51:31 Martynas Dervinis ***@***.***>:

**Comment by dervinism** [comment]
I use  util.table2nwb to create an electrode table. Overall, I am following matnwb ecephys [tutorial](https://neurodatawithoutborders.github.io/matnwb/tutorials/html/ecephys.html).

Now I've tested the latest master branch of matnwb and it gives the same error. Except now if I use cell arrays, I get a new type of error that you have recently introduced to prohibit cell arrays. Using all other types of data gives the same old error. So the issue remains not fixed. It is probably best to replicate the error using my code and example data.

**Comment by dervinism** [comment]
Also the latest matnwb introduces a new error which was not present in the previous version (see below). I will revert back to the old version.
```
Unable to resolve the name
behaviorModule.nwbdatainterface.set.

Error in convert2nwb (line 274)
  behaviorModule.nwbdatainterface.set('BehavioralTimeSeries',
  behavioralTimeSeries);
```

**Comment by lawrence-mbf** [comment]
Yes, is there a place where we can see your code? Posting example data should help too.

**Comment by lawrence-mbf** [comment]
Hi @dervinism,

I got this data working (and on R2017a as well) but the script needs a few changes in how you create and use the `table` object. I do not believe these fixes warrant any change to the MatNWB code base itself. Would you prefer the changes described here? I'm not familiar with GIN.

**Comment by dervinism** [comment]
Sure, describing here will work. Thanks for looking into my code.

**Comment by lawrence-mbf** [comment]
It really all goes back to the cell arrays. VectorData objects cannot be instantiated with cell arrays of numeric types. Their data properties only allow for conversions of:
1) cell arrays of character vectors (converted to arrays of variable length string types).
2) multi-dimensional numeric matrices (converted to their equivalents in HDF5).
3) structs, container.Map objects, and table objects (converted to compound types).
4) ObjectView/RegionView matrices (converted to references).

With the current script, your `metadata` table is attempting to create VectorData with sub-tables (of the `table` type) containing a cell array of either character vectors, numbers, or ObjectView.

This (before the addition of the assertion check) would have been mapped to a HDF5 compound data type of variable length strings because a cell array was assumed to imply a string type. This has now been fixed in master and should error. What you want to do is construct your VectorData object with a numeric vector representing your DynamicTable's column.

The simplest method would be to replace all table indexes with this: `cell2mat(metadata{:,x})` but only for numeric and ObjectView columns. There should not be any string conversions necessary for this to work.

**Comment by lawrence-mbf** [comment]
On a side note, `waveformMeans` should also be concatenated into a double matrix and not converted to a string.

**Comment by dervinism** [comment]
This info is useful but this is not the cause of the error. Even if I follow your instructions I get an error on one machine but not on the other. I even now tried different Matlab versions and they all produce the same error on one machine but not on the other. Very strange!

**Comment by lawrence-mbf** [comment]
The script with your changes works fine for me.

Can you delete the output NWB file in your cleanup script prior to running `convert2nwb`? MatNWB by will attempt to modify the NWB file otherwise.

**Comment by dervinism** [comment]
Deleting old NWB files did solve the problem in the end. Many thanks for your help!

**Comment by lawrence-mbf** [comment]
Good to see!

**Comment by lawrence-mbf** [comment]
Submit your images today! Winners of the August Image Contest   Juror's Choice Winner Perinatal Infection in the Monkey Brain Danielle Beckman California National Primate Research Center People's Choice Winner Neural-Glial-Vascular Complex Network Norberto Garcia-Cairasco Ribeirão Preto School of Medicine - University São Paulo   Thank You to everyone who entered! You are part of a growing collection of amazing images celebrating the beauty of the brain.   September Contest Now Open Share your view of the brain with us!  Enter the Contest About NeuroArt The NeuroArt image contest is a celebration of the beauty of the brain. It's a place to share your view of the brain - whether you use stains or dyes to visualize neurons under a microscope, use fMRI to analyze brain activity, or put a pencil to a piece of paper and draw your perspective. Any image, photo, drawing, or painting of the brain is accepted.   How it works NeuroArt is a monthly contest with 2 awards given each month. You can enter up to 3 images each month. Anyone over the age of 18 with an interest in neuroscience can enter.   There are two awards given each month: 1. Juror's Choice (chosen by our judging panel of scientists and artists) 2. People's Choice (image with the most number of votes)   The juror's Choice winner becomes eligible to have their image on the cover of the Journal of Neuroscience Research. People's Choice winner gets $250 towards the purchase of MBF Bioscience software or a free 3D printed brass neuron. Read all Rules and Prizes   NEW to NeuroArt Here's how to enter:   Step 1. Go to the September NeuroArt Contest Step 2. Submit up to 3 images, making sure images meet these requirements: Image must be free of labels such as scale bars, etc. Image must be submitted in JPEG or PNG format. Please note: Each contestant should also have a copy of their JPEG or PNG images available in 810 x 612 points (3375 x 2550 pixels) at a resolution of 300 dpi in TIFF format. The journal cover winner will need to submit their image in this TIFF format to appear on the cover of Journal of Neuroscience Research. Step 3. Share your images with friends. Winners will be announced early October. We request you to include as much information as possible about the image. For example: Microscopy methods used, staining techniques, region(s) of brain, neuron type(s), species and more.   Enjoy stunning images submitted by neuroscientists from around the world You are welcome to download this wallpaper collection to visually enhance your desktop. MBF Bioscience is glad to share these extraordinary images to celebrate the beauty of the brain. Enjoy! Free Download NeuroArt on Instagram Follow MBF Bioscience @mbfbioscience on Instagram to see the NeuroArt contest entries. Comment on images You can now ask questions and leave comments on images at neuroart.com.  Invite friends and colleagues to enter the contest. The more people who share their unique view of the brain, the better the contest will be.  www.neuroart.com   MBF Bioscience | 1-802-288-9290 | ***@***.***             MBF Bioscience | 185 Allen Brook Lane, Williston, VT 05495 Unsubscribe ***@***.*** Update Profile | Constant Contact Data Notice Sent by ***@***.*** powered by Try email marketing for free today!

**Comment by lawrence-mbf** [comment]
You don't want to miss this. September 2022﻿ MBF Bioscience News Highlights   Product Spotlight: Stereo Investigator® - Cleared Tissue Edition Researchers quantify cortical cell numbers in cleared tissue with new unbiased stereology technique   The Image Volume Fractionator probe, available in Stereo Investigator – Cleared Tissue Edition, enables researchers to quickly and easily quantify the number of cells in a tissue sample. Using this probe, researchers imaged the cerebral cortex and quantified the number of neurons present, including those that express proteins involved in Alzheimer’s disease and schizophrenia. This work represents the beginning of an important project to build an atlas of cortical cells, using a multi-resolution imaging pipeline. Read more   MBF Bioscience solutions for core imaging facilities To help meet the broad range of imaging and quantitative image analysis needs of scientific researchers, MBF Bioscience has developed a number of comprehensive solutions based on our state-of-the-art technology and bundled them into a productivity suite of software for use as a shared resource in core imaging-facilities or large laboratories. Read more   Letter from the president:  Looking forward to seeing you at SfN As the world slowly gets back to holding in-person meetings and gatherings, we’re noticing an important change. At recent events we’ve attended in Europe and the US, it seems all of us are putting even more emphasis, appreciation and importance on face-to-face interactions than we ever had before. Suffice it to say, all of us at MBF Bioscience are really looking forward to the SfN in-person meeting in San Diego in November. Read more Upcoming Tradeshows and Workshops ● North American Vascular Biology Organization (NAVBO) October 13 - 17, 2022, Oakland, CA   ● Society for Neuroscience  November 12 -16, 2022, San Diego, CA Winners of the August NeuroArt® Contest Juror's Choice Winner Perinatal Infection in the Monkey Brain Danielle Beckman California National Primate Research Center People's Choice Winner Neural-Glial-Vascular Complex Network Norberto Garcia-Cairasco University São Paulo Enter the contest   MBF Bioscience | 1-802-288-9290 | ***@***.***             MBF Bioscience | 185 Allen Brook Lane, Williston, VT 05495 Unsubscribe ***@***.*** Update Profile | Constant Contact Data Notice Sent by ***@***.*** powered by Try email marketing for free today!

**Comment by lawrence-mbf** [comment]
Submit your images today! An image contest celebrating the beauty of the brain The NeuroArt image contest is a celebration of the beauty of the brain. It's a place to share your view of the brain - whether you use stains or dyes to visualize neurons under a microscope, use fMRI to analyze brain activity, or put a pencil to a piece of paper and draw your perspective. Any image, photo, drawing, or painting of the brain is accepted.   October Image Contest Now Open Share your view of the brain with us!  Enter the Contest   How it works NeuroArt is a monthly contest with 2 awards given each month. You can enter up to 3 images each month. Anyone over the age of 18 with an interest in neuroscience can enter.   There are two awards given each month: 1. Juror's Choice (chosen by our judging panel of scientists and artists) 2. People's Choice (image with the most number of votes)   The juror's Choice winner becomes eligible to have their image on the cover of the Journal of Neuroscience Research. People's Choice winner gets $250 towards the purchase of MBF Bioscience software or a free 3D printed brass neuron. Read all Rules and Prizes   Here's how to enter:   Step 1. Go to the October NeuroArt Contest Step 2. Submit up to 3 images, making sure images meet these requirements: Image must be free of labels such as scale bars, etc. Image must be submitted in JPEG or PNG format. Please note: Each contestant should also have a copy of their JPEG or PNG images available in 810 x 612 points (3375 x 2550 pixels) at a resolution of 300 dpi in TIFF format. The journal cover winner will need to submit their image in this TIFF format to appear on the cover of Journal of Neuroscience Research. Step 3. Share your images with friends. Winners will be announced early November. We request you to include as much information as possible about the image. For example: Microscopy methods used, staining techniques, region(s) of brain, neuron type(s), species and more.   Enjoy stunning images submitted by neuroscientists from around the world You are welcome to download this wallpaper collection to visually enhance your desktop. MBF Bioscience is glad to share these extraordinary images to celebrate the beauty of the brain. Enjoy! Free Download NeuroArt on Instagram Follow MBF Bioscience @mbfbioscience on Instagram to see the NeuroArt contest entries. Comment on images You can now ask questions and leave comments on images at neuroart.com.  Invite friends and colleagues to enter the contest. The more people who share their unique view of the brain, the better the contest will be.  www.neuroart.com   MBF Bioscience | 1-802-288-9290 | ***@***.***             MBF Bioscience | 185 Allen Brook Lane, Williston, VT 05495 Unsubscribe ***@***.*** Update Profile | Constant Contact Data Notice Sent by ***@***.*** powered by Try email marketing for free today!

**Comment by lawrence-mbf** [comment]
Submit your images today! Winners of the October Image Contest   Juror's Choice Winner Neurons in 3D Sherin Abdelrahman King Abdullah University of Science and Technology People's Choice Winner Microglia Trying to Engulf Amyloid-Beta Kuldeep Tripathi Bar Ilan University   Thank You to everyone who entered! You are part of a growing collection of amazing images celebrating the beauty of the brain.   November Contest Now Open Share your view of the brain with us!  Enter the Contest About NeuroArt The NeuroArt image contest is a celebration of the beauty of the brain. It's a place to share your view of the brain - whether you use stains or dyes to visualize neurons under a microscope, use fMRI to analyze brain activity, or put a pencil to a piece of paper and draw your perspective. Any image, photo, drawing, or painting of the brain is accepted.   How it works NeuroArt is a monthly contest with 2 awards given each month. You can enter up to 3 images each month. Anyone over the age of 18 with an interest in neuroscience can enter.   There are two awards given each month: 1. Juror's Choice (chosen by our judging panel of scientists and artists) 2. People's Choice (image with the most number of votes)   The Juror's Choice winner becomes eligible to have their image on the cover of the Journal of Neuroscience Research. People's Choice winner gets $250 towards the purchase of MBF Bioscience software or a free 3D printed brass neuron. Read all Rules and Prizes   NEW to NeuroArt Here's how to enter:   Step 1. Go to the November NeuroArt Contest Step 2. Submit up to 3 images, making sure images meet these requirements: Image must be free of labels such as scale bars, etc. Image must be submitted in JPEG or PNG format. Please note: Each contestant should also have a copy of their JPEG or PNG images available in 810 x 612 points (3375 x 2550 pixels) at a resolution of 300 dpi in TIFF format. The journal cover winner will need to submit their image in this TIFF format to appear on the cover of Journal of Neuroscience Research. Step 3. Share your images with friends. Winners will be announced early December. We request you to include as much information as possible about the image. For example: Microscopy methods used, staining techniques, region(s) of brain, neuron type(s), species and more.   Enjoy stunning images submitted by neuroscientists from around the world You are welcome to download this wallpaper collection to visually enhance your desktop. MBF Bioscience is glad to share these extraordinary images to celebrate the beauty of the brain. Enjoy! Free Download NeuroArt on Instagram Follow MBF Bioscience @mbfbioscience on Instagram to see the NeuroArt contest entries. Comment on images You can now ask questions and leave comments on images at neuroart.com.  Invite friends and colleagues to enter the contest. The more people who share their unique view of the brain, the better the contest will be.  www.neuroart.com   MBF Bioscience | 1-802-288-9290 | ***@***.***             MBF Bioscience | 185 Allen Brook Lane, Williston, VT 05495 Unsubscribe ***@***.*** Update Profile | Constant Contact Data Notice Sent by ***@***.*** powered by Try email marketing for free today!

**Comment by rly** [comment]
@lawrence-mbf it looks like your email client sent some replies here. Can I delete them?

**Comment by lawrence-mbf** [comment]
Yeah, my bad

Nov 15, 2022 20:26:05 Ryan Ly ***@***.***>:

**Comment by lawrence-mbf** [comment]
Submit your images today! Winners of the November Image Contest   Juror's Choice Winner Neural Innervation in a Sea Star Larva Veronica Pagowski Stanford University People's Choice Winner CA1 Pyramidal Neurons Labelled with DiI Hannah Reid University of Victoria   Thank You to everyone who entered! You are part of a growing collection of amazing images celebrating the beauty of the brain.   December Contest Now Open Share your view of the brain with us!  Enter the Contest About NeuroArt The NeuroArt image contest is a celebration of the beauty of the brain. It's a place to share your view of the brain - whether you use stains or dyes to visualize neurons under a microscope, use fMRI to analyze brain activity, or put a pencil to a piece of paper and draw your perspective. Any image, photo, drawing, or painting of the brain is accepted.   How it works NeuroArt is a monthly contest with 2 awards given each month. You can enter up to 3 images each month. Anyone over the age of 18 with an interest in neuroscience can enter.   There are two awards given each month: 1. Juror's Choice (chosen by our judging panel of scientists and artists) 2. People's Choice (image with the most number of votes)   The Juror's Choice winner becomes eligible to have their image on the cover of the Journal of Neuroscience Research. People's Choice winner gets $250 towards the purchase of MBF Bioscience software or a free 3D printed brass neuron. Read all Rules and Prizes   NEW to NeuroArt Here's how to enter:   Step 1. Go to the December NeuroArt Contest Step 2. Submit up to 3 images, making sure images meet these requirements: Image must be free of labels such as scale bars, etc. Image must be submitted in JPEG or PNG format. Please note: Each contestant should also have a copy of their JPEG or PNG images available in 810 x 612 points (3375 x 2550 pixels) at a resolution of 300 dpi in TIFF format. The journal cover winner will need to submit their image in this TIFF format to appear on the cover of Journal of Neuroscience Research. Step 3. Share your images with friends. Winners will be announced early January. We request you to include as much information as possible about the image. For example: Microscopy methods used, staining techniques, region(s) of brain, neuron type(s), species and more.   Enjoy stunning images submitted by neuroscientists from around the world You are welcome to download this wallpaper collection to visually enhance your desktop. MBF Bioscience is glad to share these extraordinary images to celebrate the beauty of the brain. Enjoy! Free Download NeuroArt on Instagram Follow MBF Bioscience @mbfbioscience on Instagram to see the NeuroArt contest entries. Comment on images You can now ask questions and leave comments on images at neuroart.com.  Invite friends and colleagues to enter the contest. The more people who share their unique view of the brain, the better the contest will be.  www.neuroart.com   MBF Bioscience | 1-802-288-9290 | ***@***.***             MBF Bioscience | 185 Allen Brook Lane, Williston, VT 05495 Unsubscribe ***@***.*** Update Profile | Constant Contact Data Notice Sent by ***@***.*** powered by Try email marketing for free today!

**Comment by lawrence-mbf** [comment]
You don't want to miss this. January 2023﻿ MBF Bioscience News Highlights   Product Spotlight: ScanImage® Mini2P miniature microscope and ScanImage The developers of the innovative Mini2P microscope at the Kavli Institute use ScanImage® software and a vDAQTM all-in one data acquisition/control system to perform in-vivo imaging on a cellular scale. Together, these innovative technologies enable the study of neurons in freely behaving animals, providing valuable insights into brain function. Controlling such complex procedures can be difficult, but ScanImage simplifies these procedures and makes it easy to execute in-vivo image acquisition. Read more   Unprecedented study reveals structure-function adaptations in the facial nucleus of elephants Researchers at Humboldt University of Berlin used Stereo Investigator® to quantify cell populations in the elephant facial nucleus. In their study they discovered that the facial nucleus in elephants is much larger than in most other mammals and that it is both larger and more complex in the African elephants than in the Asian elephants in their study.  Read more   Letter from the President: Ringing in exciting new developments with the new year  We at MBF Bioscience are thrilled to contribute to the current wave of science leading us all forward. Some of the concepts energizing us at the beginning of 2023 include new technologies that enable whole-brain imaging, expansion microscopy, multiphoton in vivo microscopy and innovative light beads microscopy, and artificial intelligence in our neuroscience tool set. Read more   New software releases We are pushing out new 2023 releases of many of our software products with new enhancements and features. Please keep an eye on your inbox for details as we announce them. ﻿ Upcoming Workshops ● The Virtual International Workshop on Confocal Microscopy and Quantitative Histology March 6-10, 2023, Virtual Workshop Upcoming Tradeshows ● The Winter Conference on Brain Research  January 20-25, 2023, Snowbird, UT ● Göttingen Meeting of the German Neuroscience Society March 22-24, 2023, Göttingen, Germany ● International Conference on Learning and Memory April 26-30, 2023, Huntington Beach, CA ﻿   Winners of the December NeuroArt® Contest Juror's Choice Winner Lateral Entorhinal Cortex ﻿Kristian Moan Norwegian University of Science and Technology People's Choice Winner Neuronal Network inside Spider Net-Complex Processes Patterns ﻿ Norberto Garcia-Cairasco University São Paulo Enter the contest   MBF Bioscience | 1-802-288-9290 | ***@***.***             MBF Bioscience | 185 Allen Brook Lane, Williston, VT 05495 Unsubscribe ***@***.*** Update Profile | Constant Contact Data Notice Sent by ***@***.*** powered by Try email marketing for free today!

**Comment by lawrence-mbf** [comment]
Submit your images today! Winners of the December Image Contest   Juror's Choice Winner Lateral Entorhinal Cortex Kristian Moan Kavli Institute for Systems Neuroscience People's Choice Winner Neuronal Network Inside Spider Net-Complex Processes Patterns Norberto Garcia-Cairasco University São Paulo   Thank You to everyone who entered! You are part of a growing collection of amazing images celebrating the beauty of the brain.   January Contest Now Open Share your view of the brain with us!  Enter the Contest About NeuroArt The NeuroArt image contest is a celebration of the beauty of the brain. It's a place to share your view of the brain - whether you use stains or dyes to visualize neurons under a microscope, use fMRI to analyze brain activity, or put a pencil to a piece of paper and draw your perspective. Any image, photo, drawing, or painting of the brain is accepted.   How it works NeuroArt is a monthly contest with 2 awards given each month. You can enter up to 3 images each month. Anyone over the age of 18 with an interest in neuroscience can enter.   There are two awards given each month: 1. Juror's Choice (chosen by our judging panel of scientists and artists) 2. People's Choice (image with the most number of votes)   The Juror's Choice winner becomes eligible to have their image on the cover of the Journal of Neuroscience Research. People's Choice winner gets $250 towards the purchase of MBF Bioscience software or a free 3D printed brass neuron. Read all Rules and Prizes   NEW to NeuroArt Here's how to enter:   Step 1. Go to the January NeuroArt Contest Step 2. Submit up to 3 images, making sure images meet these requirements: Image must be free of labels such as scale bars, etc. Image must be submitted in JPEG or PNG format. Please note: Each contestant should also have a copy of their JPEG or PNG images available in 810 x 612 points (3375 x 2550 pixels) at a resolution of 300 dpi in TIFF format. The journal cover winner will need to submit their image in this TIFF format to appear on the cover of Journal of Neuroscience Research. Step 3. Share your images with friends. Winners will be announced early February. We request you to include as much information as possible about the image. For example: Microscopy methods used, staining techniques, region(s) of brain, neuron type(s), species and more.   Enjoy stunning images submitted by neuroscientists from around the world You are welcome to download this wallpaper collection to visually enhance your desktop. MBF Bioscience is glad to share these extraordinary images to celebrate the beauty of the brain. Enjoy! Free Download NeuroArt on Instagram Follow MBF Bioscience @mbfbioscience on Instagram to see the NeuroArt contest entries. Comment on images You can now ask questions and leave comments on images at neuroart.com.  Invite friends and colleagues to enter the contest. The more people who share their unique view of the brain, the better the contest will be.  www.neuroart.com   MBF Bioscience | 1-802-288-9290 | ***@***.***             MBF Bioscience | 185 Allen Brook Lane, Williston, VT 05495 Unsubscribe ***@***.*** Update Profile | Constant Contact Data Notice Sent by ***@***.*** powered by Try email marketing for free today!

**Comment by lawrence-mbf** [comment]
Submit your images today! Winner of the February Image Contest   Juror's Choice & People's Choice Winner I got the whole world in my head! Marie Karam Collège de France Thank You to everyone who entered! You are part of a growing collection of amazing images celebrating the beauty of the brain.   March Contest Now Open Share your view of the brain with us!  Enter the Contest About NeuroArt The NeuroArt image contest is a celebration of the beauty of the brain. It's a place to share your view of the brain - whether you use stains or dyes to visualize neurons under a microscope, use fMRI to analyze brain activity, or put a pencil to a piece of paper and draw your perspective. Any image, photo, drawing, or painting of the brain is accepted.   How it works NeuroArt is a monthly contest with 2 awards given each month. You can enter up to 3 images each month. Anyone over the age of 18 with an interest in neuroscience can enter.   There are two awards given each month: 1. Juror's Choice (chosen by our judging panel of scientists and artists) 2. People's Choice (image with the most number of votes)   The Juror's Choice winner becomes eligible to have their image on the cover of the Journal of Neuroscience Research. People's Choice winner gets $250 towards the purchase of MBF Bioscience software or a free 3D printed brass neuron. Read all Rules and Prizes   NEW to NeuroArt Here's how to enter:   Step 1. Go to the March NeuroArt Contest Step 2. Submit up to 3 images, making sure images meet these requirements: Image must be free of labels such as scale bars, etc. Image must be submitted in JPEG or PNG format. Please note: Each contestant should also have a copy of their JPEG or PNG images available in 810 x 612 points (3375 x 2550 pixels) at a resolution of 300 dpi in TIFF format. The journal cover winner will need to submit their image in this TIFF format to appear on the cover of Journal of Neuroscience Research. Step 3. Share your images with friends. Winners will be announced early April. We request you to include as much information as possible about the image. For example: Microscopy methods used, staining techniques, region(s) of brain, neuron type(s), species and more.   Enjoy stunning images submitted by neuroscientists from around the world You are welcome to download this wallpaper collection to visually enhance your desktop. MBF Bioscience is glad to share these extraordinary images to celebrate the beauty of the brain. Enjoy! Free Download NeuroArt on Instagram Follow MBF Bioscience @mbfbioscience on Instagram to see the NeuroArt contest entries. Comment on images You can now ask questions and leave comments on images at neuroart.com.  Invite friends and colleagues to enter the contest. The more people who share their unique view of the brain, the better the contest will be.  www.neuroart.com   MBF Bioscience | 1-802-288-9290 | ***@***.***             MBF Bioscience | 185 Allen Brook Lane, Williston, VT 05495 Unsubscribe ***@***.*** Update Profile | Constant Contact Data Notice Sent by ***@***.*** powered by Try email marketing for free today!
