### ISSUE TITLE
[Bug]: error reading NWB file created with MatNWB tutorials

### ISSUE THREAD

**Issue by vncntprvst** [NeurodataWithoutBorders/matnwb#468]
### What happened?

The command `read_nwbfile = nwbRead('intro_tutorial.nwb')` returns this error:  
```
Check for incorrect argument data type or missing argument in call
to function 'isKey'.
```
The same error occurs with any .nwb file created from the tutorials. 
A `NamespaceData` appears to be empty, which trips the call `requiredKeysExist = isKey(Map, 'name') && isKey(Map, 'schema');` in `getNamespaceInfo/getInfo`.

### Steps to Reproduce

```matlab
Generate a .nwb file with one of the tutorials (e.g., https://neurodatawithoutborders.github.io/matnwb/tutorials/html/intro.html). Then load it with `nwbRead`.
```

### Error Message

```matlab
Check for incorrect argument data type or missing argument in call
to function 'isKey'.

Error in spec.getNamespaceInfo/getInfo (line 14)
        requiredKeysExist = isKey(Map, 'name') && isKey(Map, 'schema');

Error in spec.getNamespaceInfo (line 9)
    NamespaceData(iInfo) = getInfo(namespaceMap{iInfo});

Error in spec.generate (line 8)
Namespaces = spec.getNamespaceInfo(namespace);

Error in nwbRead>generateSpec (line 119)
    Namespaces = spec.generate(namespaceText, schemaMap);

Error in nwbRead (line 54)
        generateSpec(filename, h5info(filename, specLocation), 'savedir', saveDir);
```

### Operating System

Windows

### Matlab Version

R2021b

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/matnwb/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

**Comment by lawrence-mbf** [comment]
Hi @vncntprvst I am unable to recreate this with the intro script using both the tip of master as well as the most recent release. Which version of MatNWB are you using?

**Comment by vncntprvst** [comment]
Hi @lawrence-mbf. I'm using the current Github version. 
I can use the v2.5 release instead and see if it works. 
Thanks

**Comment by lawrence-mbf** [comment]
Hi @vncntprvst That's what I mean by the tip of the master branch. Did you run `generateCore` before running the intro script? It's listed as an instruction but is not actually in a code block it looks like.

**Comment by bendichter** [comment]
@vncntprvst try re-cloning, then regenerating and make sure there aren't any other matnwb repos in the path

**Comment by vncntprvst** [comment]
Re-cloning the repo fixed this issue. I have no idea what was wrong with the old one. 
Thanks for the help!
