### ISSUE TITLE
[Documentation]: support for PyNWB's cached schemas is not documented

### ISSUE THREAD

**Issue by vncntprvst** [NeurodataWithoutBorders/matnwb#473]
### What would you like changed or added to the documentation and why?

Hi,
The documentation says:
"PyNWB's cached schemas are also supported, bypassing the need to run generateCore or generateExtension if present."

It is unclear how install and use those cached schemas, or even what purpose it would serve. 
For example, does this enable using NWB extensions that have been developed for PyNWB?  

Adding examples here would be useful. 
Thanks

### Do you have any interest in helping write or edit the documentation?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/matnwb/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

**Comment by bendichter** [comment]
Any file written in PyNWB, including those with extensions, will be readable in MATLAB without needing to generate the API of the core nor extensions, as long as the schema(s) are cached (which is default)

**Comment by vncntprvst** [comment]
I see. Thanks for the clarification. 
I can send a PR to update that section of the documentation accordingly, if you think that's worth it.

**Comment by lawrence-mbf** [comment]
It would be nice for sure! Though if you don't wish to, I will need to know where this documentation actually is so it can be edited.
