### ISSUE TITLE
[Documentation]: Tutorials following best practices specified by the NWBInspector 

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/matnwb#484]
### What would you like changed or added to the documentation and why?

The following issue raised on PyNWB https://github.com/NeurodataWithoutBorders/pynwb/issues/1628 I believe is also relevant for MatNWB. 

**Proposed Enhancement** Enhance the test suite for the tutorials to run the NWBInspector on all files created by the tutorials to ensure that the files created by the tutorials follow best practices. 

### Do you have any interest in helping write or edit the documentation?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/matnwb/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

**Comment by ehennestad** [comment]
@oruebel Would you suggest to use Importance level 0, 1 or 2 as a threshold for test failure?

```
ERROR = 4
PYNWB_VALIDATION = 3
CRITICAL = 2
BEST_PRACTICE_VIOLATION = 1
BEST_PRACTICE_SUGGESTION = 0
```

https://github.com/NeurodataWithoutBorders/nwbinspector/blob/c26924b89c8cbcd35a6e70ae04a5fc323d4bd92b/src/nwbinspector/_types.py#L8-L15
