### ISSUE TITLE
[Bug]: Multi-dimensional type checking

### ISSUE THREAD

**Issue by owoolnough** [NeurodataWithoutBorders/matnwb#487]
### What happened?

Recently updated to MatNWB 2.6 and I came across an error in the data type checking while encoding a new file. nwbExport calls the 'correctType' script in +utils but the current version only handles 1 dimensional arrays so errored out when a 3 x n array was input as part of the ndx-ecog extension. It seems to be an easy fix on line 50 of correctType:

Original:
            assert(all(castedValue == val), ...
Updated:
            assert(all(castedValue == val,'all'), ...

### Steps to Reproduce

```matlab
N/A
```

### Operating System

macOS

### Matlab Version

Matlab 2020a

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/matnwb/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

**Comment by lawrence-mbf** [comment]
Thank you for pointing this out! Unfortunately your fix wouldn't work for versions of MATLAB older than R2018b but it's still doable if you vectorize both sides

```MATLAB
assert(all(castedValue(:) == val(:)), ...
```

**Comment by lawrence-mbf** [comment]
Hi @owoolnough, since the fix is different and there were no reproduction steps, can you verify that this PR is correct? #488
