### ISSUE TITLE
Function to read all names of objects inside nwb.acquisition

### ISSUE THREAD

**Issue by GoktugAlkan** [NeurodataWithoutBorders/matnwb#500]
Hello,

I converted a large dataset to nwb and there are multiple `ElectricalSeries` objects inside `nwb.acquisition`. Each object has a unique name. 

I am wondering if there is a function that returns a list of the names of the objects inside `nwb.acquisition`. Is there such a function?

Many thanks in advance!

**Comment by bendichter** [comment]
@GoktugAlkan that seems like the best approach to me. OK to close?

**Comment by GoktugAlkan** [comment]
Yes, can be closed. Thanks!
