### ISSUE TITLE
Visualize DynamicTable

### ISSUE THREAD

**Issue by GoktugAlkan** [NeurodataWithoutBorders/matnwb#501]
Hello,

I am struggling to visualize a DynamicTable after reading a stored nwb file (called `nwbfile` in the code) with `nwbRead`. A more detailed description is below:

1. Read raw electrophysiologic signals. 
2. Create a table with the information about the electrodes that were used to record the raw data (note: this is a dynamic table object and called `electrode_table` in the code).
3. Insert the electrodes table inside the `nwbfile` by executing `nwbfile.general_extracellular_ephys_electrodes = electrode_table`.
4. Store `nwbfile` with the command `nwbExport`.

Before storing `nwbfile`, i.e., before step 4, it is possible to visualize the electrodes table by executing `nwbfile.general_extracellular_ephys_electrodes` in the command window. 

However, after storing `nwbfile` and reading it and executing again `nwbfile.general_extracellular_ephys_electrodes` in the command window, you do not get the visualization of the table anymore as before. 

When you read the same stored `nwbfile` in `python` (by using `pynwb`) and use `nwbfile.electrodes.to_dataframe()`, you get the visualization of the table.

I would like to know if there exists an equivalent function like `to_dataframe()` which I could use in `matlab` to visualize a dynamic table after reading a stored nwb file. 

Many thanks in advance!

**Comment by lawrence-mbf** [comment]
Hi @GoktugAlkan ,

If you're using a regular `DynamicTable` object, then you can use its `toTable` method which should be able to show you the saved dataset as a MATLAB `table` object. This should work for most `DynamicTable` objects.

**Comment by lawrence-mbf** [comment]
Just a warning, however, that this does load the entire dataset and may be a bit slow if there are many columns.

**Comment by GoktugAlkan** [comment]
Thanks a lot, it's working! The table is not very large, so loading it just takes 1 second. 

Thanks!
