### ISSUE TITLE
MatNWB fails to read NWB file after updating to latest version[Bug]: 

### ISSUE THREAD

**Issue by chinmayeelm** [NeurodataWithoutBorders/matnwb#504]
### What happened?

I installed the latest version of matNWB. I am trying to read the NWB files written with the old version of matNWB (may be before 2.0.2). Unable to read the file with any of the latest cores above 2.0.2. I am getting the following error.

![image](https://user-images.githubusercontent.com/25946537/236130949-7690b0da-fea3-4b27-8c7b-1983f60187b1.png)

### Steps to Reproduce

```matlab
Download latest version. 
Generate core.
Open the an nwb file generated by old core. (I am unable to attach my NWB file.)
```

### Error Message

```matlab
nwb = nwbRead('M1_N1_blwgn.nwb');
Error using types.util.checkDims
Value of size [5 1] is invalid.  Must be one of:
    - Rank 1 with dimensions of size: [1]

Error in types.core.NWBFile/validate_general_stimulus (line 688)
        types.util.checkDims(valsz, validshapes);

Error in types.core.NWBFile/set.general_stimulus (line 273)
        obj.general_stimulus = obj.validate_general_stimulus(val);

Error in types.core.NWBFile (line 156)
        obj.general_stimulus = p.Results.general_stimulus;

Error in NwbFile (line 16)
            obj = obj@types.core.NWBFile(varargin{:});

Error in io.parseGroup (line 76)
            parsed = NwbFile(kwargs{:});

Error in nwbRead (line 59)
nwb = io.parseGroup(filename, h5info(filename), Blacklist);
```

### Operating System

Windows

### Matlab Version

Matlab 2023a

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/matnwb/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

**Comment by chinmayeelm** [comment]
I checked the attributes. The version is 2.2.4
After reverting to old version, I can read the files. 
Back compatibility would be appreciated. This issue can be close otherwise.

**Comment by chinmayeelm** [comment]
It doesn't work with version 2.0.2 either.

**Comment by chinmayeelm** [comment]
I should have been clearer. I downloaded the latest MatNWB and built the core 2.2.4 using the command 
`generateCore('2.2.4');`
and I get same error as I posted in the first message.

**Comment by lawrence-mbf** [comment]
Interesting. The type of `/general/stimulus` should be an optional scalar text. Do you know what the value of that value actually is? Either a HDFView screenshot or the output in a working version of MatNWB should work.

**Comment by chinmayeelm** [comment]
It is a string (as loaded in matlab). 
![image](https://user-images.githubusercontent.com/25946537/236507717-65edcfd1-2935-49f0-9323-4b37ada93cf0.png)
![image](https://user-images.githubusercontent.com/25946537/236508212-22a330c6-4f6d-4354-896e-7703bdba3534.png)
There are no attributes for this.

**Comment by lawrence-mbf** [comment]
This is probably asking too much but does that data make sense to you as a `/general/stimulus` field? If this really is an array of strings, it violates the schema for `2.2.4` but without knowing the context I can't really offer advice on rewriting that part. It probably should have been caught in the older MatNWB version unfortunately.

**Comment by chinmayeelm** [comment]
Yes. This data makes sense. These are parameters for my experiment. For some unknown reason, I have converted the array into string array before writing to the NWB file. I can re-write it for my future experiments. Guess I am stuck with this for my old files. 

Thanks a lot for helping out.
