### ISSUE TITLE
[Bug]: DateString Interpretation Error in io.parseDataset()

### ISSUE THREAD

**Issue by taoizm** [NeurodataWithoutBorders/matnwb#508]
### What happened?

I discovered an issue when trying to open .nwb files using the 'nwbRead' function due to an error occurring within 'io.parseDataset()'.

Specifically, on line 34 of 'io.parseDataset()', the datetime() function attempts to interpret a string returned by `version('-date')`. For example, if using R2022b, `version('-date')` returns a string like 'November 17, 2022'. However, if the system locale cannot interpret these DateStrings, it results in an error.

In my environment, the locale is set to 'jp_JP'. Based on my research, locales 'fr_FR', 'it_IT', 'ko_KR', and 'zh_CN' also struggle with interpreting these DateStrings.

A workaround that I found to be effective is to modify line 34 as follows:
```matlab
if datetime(version('-date'),'Locale','en_US') < datetime('25-Feb-2020','Locale','en_US')
```
This modification solved the issue in my environment.

### Steps to Reproduce

```matlab
nwb2 = nwbRead('ecephys_tutorial.nwb')
```

### Error Message

```matlab
% Unfortunately, the error message I received was in Japanese due to my locale 
% settings. The essence of the error message is that the system locale cannot 
% interpret the DateStrings returned by version('-date'), causing the error.

次を使用中: datetime
'November 17, 2022' の日付/時刻の形式を認識できませんでした。'InputFormat' パ
ラメーターを使用して、形式を指定できます。日付/時刻のテキストに 'ja_JP' ロケ
ールと異なる言語の曜日、月またはタイム ゾーンの名前が含まれている場合、それ
らは認識されないことがあります。'Locale' パラメーターを使用して異なるロケー
ルを指定できます。

エラー: io.parseDataset (行 34)
            if datetime(version('-date')) < datetime('25-Feb-2020')

エラー: io.parseGroup (行 22)
    dataset = io.parseDataset(filename, datasetInfo, fullPath, Blacklist);

エラー: nwbRead (行 59)
nwb = io.parseGroup(filename, h5info(filename), Blacklist);
```

### Operating System

Windows

### Matlab Version

R2022b

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/matnwb/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

**Comment by lawrence-mbf** [comment]
This should probably be using `ver` instead of `version` since the check appears to be for MATLAB version checks.

**Comment by lawrence-mbf** [comment]
Hi @taoizm . When you get the time, please let me know if PR #509 works for you.

**Comment by taoizm** [comment]
It works! Thank you for the suggestion.
