### ISSUE TITLE
Removing data from an already existing nwb file

### ISSUE THREAD

**Issue by GoktugAlkan** [NeurodataWithoutBorders/matnwb#510]
Hello,

Currently, I am trying to remove data from an already existing nwb file. There is an nwb file that is stored on the disk and that I load with `nwbRead`. I want to remove the data in the field `nwb.units`. However, I couldn't find a method like the pop-method that exists in `pyNWB` (explained [here](https://pynwb.readthedocs.io/en/stable/tutorials/general/add_remove_containers.html)). Is there a way to resolve this issue?

**Background of issue:**
We created nwb files containing raw data and information on spike times/spike clusters/waveforms that are stored in `nwb.units` as proposed in your tutorials/explanations. After creating these files, we tuned again our spike sorting algorithm to get cleaner units. Hence, we need to change the information stored in `nwb.units`. That's why I am trying to delete the data in this field and to populate the field with the latest information about the spikes. We want to avoid the creation of a file from scratch. 

Many thanks in advance!

**Comment by lawrence-mbf** [comment]
Sorry for not getting back to you last week.

By default MatNWB should support rewriting attributes. For datasets, the rewrite must be the same shape as before.

**Comment by lawrence-mbf** [comment]
By the way, this is done by exporting an open NWB file to its original file location so you don't have to create the Nwb object from scratch.

**Comment by GoktugAlkan** [comment]
@lawrence-mbf Thanks for the response. The problem is that the dataset that we want to insert may be significantly different than the one that was already existing. For example, we may have 1000 spikes less than before. Hence, the shape of the dataset would not be preserved. 

Therefore, instead of overwriting this field, my idea was to delete all data inside `nwb.units` first and then populate this field with our revisited spike information. Finally, I wanted to store this file on the same location.

What would be the best way to realize this?

Thanks in advance!

**Comment by lawrence-mbf** [comment]
@GoktugAlkan For attributes you can always use [H5A.delete](https://www.mathworks.com/help/matlab/ref/attributeh5a.html) for data you don't need.

For datasets there's currently no way that I've found to rewrite AND resize the data without using chunking. I wonder what pynwb is actually doing under the hood for the `pop` method because even low-level MATLAB calls are unable to delete dataset containers as far as I can tell.

The only other way I've found is to possibly bloat your file by "unlinking" the data and repacking: https://www.mathworks.com/matlabcentral/answers/395920-how-can-i-delete-a-dataset-completely-from-a-group-in-a-hdf5-file

No clue how performant this actually is.

**Comment by GoktugAlkan** [comment]
@lawrence-mbf Thanks a lot. With the functions in the provided link I am able to delete the field `nwb.units`. I will inform you soon with my final conclusion.

**Comment by GoktugAlkan** [comment]
@bendichter Thanks! Concerning this point, I guess that when the data that I want to insert into the deleted field is bigger than the previous data (i.e. bigger than the space that the deleted object take up in the file) there should be no problem. Is this correct?

**Comment by lawrence-mbf** [comment]
@GoktugAlkan There is no such guarantee unless you use chunking and/or h5repack. Unlinking just removes references to the data but still keeps the allocated space around. I suppose you can test that out but it's really up to the HDF5 driver to organize that data.

**Comment by GoktugAlkan** [comment]
@lawrence-mbf @bendichter  Since I am preparing the pipelines for lab members who use MATLAB, it would be very convenient to write a MATLAB function to apply this repacking. However, it seems that this is not possible in this case. I will try to apply the repacking and inform you about the progress. 

If possible, it would be nice to have a method like pop as in pyNWB that applies the resizing/repacking of the file.

**Comment by bendichter** [comment]
PyNWB has the same issue. If you want to remove a dataset and free the space, you either need to write everything to a new file or use h5repack.

**Comment by GoktugAlkan** [comment]
@bendichter @lawrence-mbf The repacking works. I tested this on an nwb file, where I deleted the acquisition field. After removing that field, the new nwb file still occupied the same storage. But after using h5repack, the storage of the nwb file decreased significantly.
