### ISSUE TITLE
[Bug]: convertTrials Tutorial uses Out of Date Syntax

### ISSUE THREAD

**Issue by jc192015** [NeurodataWithoutBorders/matnwb#515]
### What happened?

When running matnwb(2.6.0), I got an error message. I am wondering that is due to a bug with matnwb. Or Could you please let me know how to fix it?
Thank you in advance for your time and help. 

### Steps to Reproduce

```matlab
nwb = NwbFile();
nwb.units = types.core.Units('colnames',...
    {'spike_times', 'trials', 'waveforms'},...
    'description', 'Analysed Spike Events');
```

### Error Message

```matlab
Error using assert
Value of type `types.core.ElementIdentifiers` cannot be converted to type `types.hdmf_common.ElementIdentifiers`.

Error in types.util.correctType (line 60)
        assert(isa(val, type), ...

Error in types.util.checkDtype (line 96)
correctedValue = types.util.correctType(val, type);

Error in types.hdmf_common.DynamicTable/validate_id (line 90)
        val = types.util.checkDtype('id', 'types.hdmf_common.ElementIdentifiers', val);

Error in types.hdmf_common.DynamicTable/set.id (line 46)
        obj.id = obj.validate_id(val);

Error in types.util.dynamictable.checkConfig (line 58)
            DynamicTable.id = types.core.ElementIdentifiers('data', idData);

Error in types.core.Units (line 60)
            types.util.dynamictable.checkConfig(obj);
```

### Operating System

Windows

### Matlab Version

Matlab R2023a

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/matnwb/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

**Comment by bendichter** [comment]
It looks like you should be able to fix this by deleting your MatNWB folder and downloading it again

**Comment by bendichter** [comment]
I cannot reproduce. Can you please make sure you MatNWB is up-to-date? If you used `git clone` you might be able to simply call `!git pull` inside MATLAB while in the matnwb repo

**Comment by bendichter** [comment]
If that doesn't work, you can delete MatNWB and download it again from here.

**Comment by jc192015** [comment]
Hi there,

After deleting Matnwb and downloading it again, the mentioned problem has been resolved.
 Thank you.

But I got another error message when I tried to run the script "MatNWB\tutorials\convertTrials.m."

code at line 351:
  trials_epoch = types.core.TimeIntervals(...
                         'start_time', types.hdmf_common.VectorData('data', data.trialStartTimes,...
                         'description', 'Start time of epoch, in seconds.'),...
                          'colnames', [data.trialTypeStr; data.trialPropertiesHash.keyNames .';...
                                          {'start_time'; 'stop_time'; 'acquisition'; 'timeseries'}],...
                          'description', 'trial data and properties', ...
                         'id', types.hdmf_common.ElementIdentifiers('data', data.trialIds),...
                         'timeseries', types.hdmf_common.VectorData('description', 'Index into timeseries Data'),...
                        'timeseries_index', types.hdmf_common.VectorIndex(...
                        'description', 'Index into Timeseries VectorData',...
                        'target', types.untyped.ObjectView('/intervals/trials/timeseries')));

Error Message:
Error using assert
Value of type `types.hdmf_common.VectorData` cannot be converted to type `types.core.TimeSeriesReferenceVectorData`.

Error in types.util.correctType (line 60)
        assert(isa(val, type), ...

Error in types.util.checkDtype (line 96)
correctedValue = types.util.correctType(val, type);

Error in types.core.TimeIntervals/validate_timeseries (line 82)
        val = types.util.checkDtype('timeseries', 'types.core.TimeSeriesReferenceVectorData', val);

Error in types.core.TimeIntervals/set.timeseries (line 62)
        obj.timeseries = obj.validate_timeseries(val);

Error in types.core.TimeIntervals (line 39)
        obj.timeseries = p.Results.timeseries;

Error in convertTrials4jia (line 407)
trials_epoch = types.core.TimeIntervals(...

________________________________

**Comment by bendichter** [comment]
yeah, this looks like outdated code

**Comment by jc192015** [comment]
So do you have an updated  convertTrials.m?

**Comment by lawrence-mbf** [comment]
The code was probably added before validation changes to `DynamicTable` objects like `TimeIntervals`. There's no `stop_time` data for instance so the code needs to be reworked to include that.
