### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jc192015** [NeurodataWithoutBorders/matnwb#516]
### What happened?

Failed to create a TimeIntervals table. I am wondering if there is something with the installed MatNWB (2.6.0).
Thank you in advance for your time.

### Steps to Reproduce

```matlab
trialTypeStr = {'HitR';
    'HitL';
    'ErrR';
    'ErrL';
    'NoLickR';
    'NoLickL';
    'LickEarly';
    'StimTrials'};
    
keyNames = {'PoleInTime',    'PoleOutTime',    'CueTime' ,   'GoodTrials',    'Photostimulatio…'};

trialIds = [1:213];

trials_epoch = types.core.TimeIntervals(...
      'colnames', [trialTypeStr; keyNames .';...
        {'start_time'; 'stop_time'; 'acquisition'; 'timeseries'}],...
    'description', 'trial data and properties', ...
    'id', types.hdmf_common.ElementIdentifiers('data', trialIds));
```

### Error Message

```matlab
Error using assert
Special column `id` of DynamicTable needs to match the detected height of 0. Found 213 IDs.

Error in types.util.dynamictable.checkConfig (line 65)
    assert(tableHeight == getVectorHeight(DynamicTable.id), ...

Error in types.core.TimeIntervals (line 45)
            types.util.dynamictable.checkConfig(obj);
```

### Operating System

Windows

### Matlab Version

R2023a

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/matnwb/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

**Comment by jc192015** [comment]
P {margin-top:0;margin-bottom:0;}

**Comment by lawrence-mbf** [comment]
Continued in #527
