### ISSUE TITLE
[Documentation]: create read tutorial with newer indexing

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#535]
### What would you like changed or added to the documentation and why?

The read tutorial currently only demonstrates old awkward indexing syntax

### Do you have any interest in helping write or edit the documentation?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/matnwb/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

**Comment by lawrence-mbf** [comment]
There, in fact, appears to be no read tutorial (there is but not the one presented).

[Here is the link](https://mbfbioscience-my.sharepoint.com/:u:/p/lawrence/EbAaWua2LONKqMc3ONIjI_IBm7yBHr82yuAWT4QAkqikCQ?e=jr7A3c) to the talk given by @rly as reference

**Comment by oruebel** [comment]
There is a read guide on nwb-overview that may be relevant for this issue:

https://nwb-overview.readthedocs.io/en/latest/file_read/file_read.html#reading-with-matnwb
