### ISSUE TITLE
[Bug]:  file create date is not appendable if the file is generated by pynwb

### ISSUE THREAD

**Issue by laurelrr** [NeurodataWithoutBorders/matnwb#550]
### What happened?

I recently created an nwb file using the tye-lab-to-nwb neurotensin package on github (a pynwb package).  Later, I wanted to change some of the general fields and loaded the file into matlab:
```
 > nwb = nwbRead('H07_DiscS.nwb');
 > nwb.general_subject.age = 'P109D';
 > nwbExport(nwb,'H07_DiscS.nwb')
```
but this gave me an error:
```
Warning: Attempted to change size of continuous dataset `/file_create_date`.  Skipping.
> In io.writeDataset (line 26)
In types.core/NWBFile/export (line 849)
In NwbFile/export (line 66)
In nwbExport (line 42)  
```
I expected this to write out an updated NWB file. However, the export function tries to add a second date into the 'file_create_date' field:
```
>> nwb.file_create_date
ans =
  1×2 cell array
    {[2023-10-10T14:38:34.356656-07:00]}    {[2023-10-20T14:54:46.150750-07:00]}
```

I am working on Windows 11, using Matlab 9.14.0.2286388 (R2023a) Update 3, with matnwb version 2.6.0. installed.
The original file was 'auto-generated using neuroconv'.

### Steps to Reproduce

```matlab
(Using python, inside tye-lab-to-nwb folder)
> conda activate tyenwbevn39
> python src/tye_lab_to_nwb/neurotensin_valence/neurotensin_valence_convert_all_sessions.py

(In matlab)
 > nwb = nwbRead('H07_DiscS.nwb');
 > nwb.general_subject.age = 'P109D';
 > nwbExport(nwb,'H07_DiscS.nwb')
```

### Error Message

```matlab
Warning: Attempted to change size of continuous dataset `/file_create_date`.  Skipping.
> In io.writeDataset (line 26)
In types.core/NWBFile/export (line 849)
In NwbFile/export (line 66)
In nwbExport (line 42)
```

### Operating System

Windows

### Matlab Version

 9.14.0.2286388 (R2023a) Update 3

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/matnwb/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

**Comment by lawrence-mbf** [comment]
This warning message is actually somewhat expected and, indeed, is intended for compatibility with pynwb already since the behavior for editing files in MatNWB will differ slightly from pynwb regarding `/file_create_date`.
