### ISSUE TITLE
[Bug]: Cannot store spatial data with time as first dimension

### ISSUE THREAD

**Issue by NeuroGuth** [NeurodataWithoutBorders/matnwb#563]
### What happened?

Hello everyone,

When trying to store a [ntime * ndata] array in a SpatialSeries object, I get the error below. It says that the array should be [ndata * ntime], but this is not in line with the description on "https://neurodatawithoutborders.github.io/matnwb/doc/+types/+core/SpatialSeries.html" and also different from Python. Is this intended?

Best,  Tim

### Steps to Reproduce

```matlab
spatialSeries = types.core.SpatialSeries('data', [linspace(1, 100, 100)', linspace(1, 100, 100)']);
```

### Error Message

```matlab
Error using types.util.checkDims
Value of size [100 2] is invalid.  Must be one of:
    - Rank 2 with dimensions of size: [3 Any]
    - Rank 2 with dimensions of size: [2 Any]
    - Rank 2 with dimensions of size: [1 Any]
    - Rank 1 with dimensions of size: [Any]
Error in types.core.SpatialSeries/validate_data (line 63)
        types.util.checkDims(valsz, validshapes);
Error in types.core.TimeSeries/set.data (line 91)
        obj.data = obj.validate_data(val);
```

### Operating System

Windows

### Matlab Version

R2023a

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/matnwb/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

**Comment by lawrence-mbf** [comment]
Yes, this is a quirk of how MATLAB chooses to order data. See https://github.com/NeurodataWithoutBorders/matnwb?tab=readme-ov-file#data-dimensions

**Comment by NeuroGuth** [comment]
all right, thank you very much for the answer!
