### ISSUE TITLE
Unrecognized function or variable 'Schema'.[Bug]: 

### ISSUE THREAD

**Issue by amadaabrego** [NeurodataWithoutBorders/matnwb#565]
### What happened?

Hey everyone, whenever I'm generating a core I get the below error. I have tried to debug it myself, but I do not find anything wrong. The java_loc and nwb_loc folders/paths seem to be correct. So, I have no idea what might be going on. Could there be an error with the schema.jar file?

Before reading a file, I exported a couple of them, and I didn't have an issue with the code. I realized just now that it saved it in the 2.2.5 schema. I do not know why! 

> In javaclasspath
In javaclasspath
In javaaddpath (line 71)
In spec.loadSchemaObject (line 9)
In spec.generate (line 6)
In generateExtension (line 53)
In generateCore (line 52)
In spec.loadSchemaObject (line 9)
In spec.generate (line 6)
In generateExtension (line 53)
In generateCore (line 41)
In spec.loadSchemaObject (line 9)
In spec.generate (line 6)
In generateExtension (line 53)
In generateCore (line 52) 
Unrecognized function or variable 'Schema'.

### Steps to Reproduce

```matlab
function schema = loadSchemaObject()
%LOADSCHEMAOBJECT Loads YAML reader from jar
%   Returns a Java object which can read() yaml text
try
    schema = Schema();
catch
    nwb_loc = fileparts(which('NwbFile'));
    java_loc = fullfile(nwb_loc, 'jar', 'schema.jar');
    javaaddpath(java_loc);
    schema = Schema();
end
end
```

### Error Message

```matlab
> In javaclasspath
In javaclasspath
In javaaddpath (line 71)
In spec.loadSchemaObject (line 9)
In spec.generate (line 6)
In generateExtension (line 53)
In generateCore (line 52)
In spec.loadSchemaObject (line 9)
In spec.generate (line 6)
In generateExtension (line 53)
In generateCore (line 41)
In spec.loadSchemaObject (line 9)
In spec.generate (line 6)
In generateExtension (line 53)
In generateCore (line 52) 
Unrecognized function or variable 'Schema'.
```

### Operating System

macOS

### Matlab Version

2023b

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/matnwb/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

**Comment by lawrence-mbf** [comment]
Does the result of `which spec.loadSchemaObject` return what you expect it to? What version of MatNWB are you using? I am unable to recreate the issue and the CI should fail if `schema.jar` is corrupted.

Your issue with writing the wrong schema version may be a result of multiple MatNWB generated types on your MATLAB path. Check your path to see if you are referencing the correct MATLAB types with `which`. If you are writing, I would suggest calling `nwbClearGenerated()` and `generateCore()` to wipe any previously generated types before generating the types necessary.

**Comment by amadaabrego** [comment]
That worked! Thanks.
