### ISSUE TITLE
[Documentation]: Special tutorial page on Tables

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#571]
### What would you like changed or added to the documentation and why?

Should demonstrate construction modes:
* conversion from MATLAB table
* direct declaration
* addRow

should also cover conversion to Table

### Do you have any interest in helping write or edit the documentation?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/matnwb/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

**Comment by ehennestad** [comment]
Todo:
Create PR from issue branch with proposed fixes
