### ISSUE TITLE
cannot read new Units table

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#58]
The schema has a new table called Units which cannot be read by matnwb.

```matlab
nwbRead('test_units.nwb')
Error using types.util.checkDtype (line 58)
Property `id` must be a types.core.ElementIdentifiers.

Error in types.core.DynamicTable/validate_id (line 56)
        val = types.util.checkDtype('id',
        'types.core.ElementIdentifiers', val);

Error in types.core.DynamicTable/set.id (line 42)
        obj.id = obj.validate_id(val);

Error in types.core.DynamicTable (line 37)
        obj.id = p.Results.id;

Error in io.parseGroup (line 68)
    parsed = eval([typename '(kwargs{:})']);

Error in io.parseGroup (line 26)
    subg = io.parseGroup(filename, g_info);

Error in nwbRead (line 20)
nwb = io.parseGroup(filename, info);
```

[example file](https://www.dropbox.com/s/tt9ikiq4n0aiahz/test_units.nwb?dl=0)

**Comment by ln-vidrio** [comment]
This is related to #43.
The `neurodata_type_def` for `DynamicTable` defines `id` as an `ElementIdentifier`, but is now, specifically for `units`, rewritten for all `DynamicTable` objects and subclasses.  Matnwb assumes that all property definitions with a `neurodata_type_def` are immutable unless subclassed, so fixing this on our side will require weakening assumptions about type definitions and how validations work.
One way to get around this is to define your own `DynamicTable` subclass and match its definition with the one presented in `units`.  Validations will work fine then.

**Comment by bendichter** [comment]
I suspected something to this effect. It sounds like this will be better to fix on the pynwb side.

**Comment by oruebel** [comment]
@ajtritt can you have a look at this. This looks like a bug in the schema.
