### ISSUE TITLE
how to construct trials table?

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#59]
We have it working that you can create a dynamictable in pynwb and read it in matnwb, but I do not know how to do the reverse. Can you give me a minimal example for constructing a trials or units table in matnwb?

**Comment by ln-vidrio** [comment]
For trials:
```
columnNames = {'start'};
nwb.trials = types.core.DynamicTable(...
    'colnames', columnNames,...
    'description', 'trial data and properties', ...
    'id', types.core.ElementIdentifiers('data', 1:10));

for i=1:length(columnNames)
    nwb.trials.tablecolumn.set(columnNames{i}, ...
        types.core.TableColumn('data', <some vector>));
end
```
Things to note that may impact compatibility:
1. There are no checks for guaranteeing that the names in colnames match the entries in tablecolumn.
2. There are no checks guaranteeing rectangular shape of the DynamicTable (that all columns have the same number of elements as the `id`)
3. #43 so the the presence of a 'start' column is not checked for, either in name or as a tablecolumn entry.

**Comment by bendichter** [comment]
perfect! Thanks for the speedy response!

**Comment by ln-vidrio** [comment]
Is there an error message?  It runs fine on my machine.

**Comment by bendichter** [comment]
hmm let me update
