### ISSUE TITLE
Parsed dtype for attributes and datasets are incomplete and some are unexpected

### ISSUE THREAD

**Issue by mcafaro** [NeurodataWithoutBorders/matnwb#6]
Some of the attribute and dataset dtypes listed in the schema spec do not appear to be handled properly. For instance, I would expect ascii, utf, utf8, utf-8 to be parsed as string like text but they are left as is. Others are handled in unexpected ways (float is parsed as double instead of single).

***Failing tests:***
```matlab
>> nwbtest('ProcedureName', 'testParseAttributeWithDtype')
>> nwbtest('ProcedureName', 'testParseDatasetWithDtype')
```

**Comment by lawrence-mbf** [comment]
Closed as stale.
