### ISSUE TITLE
[Feature]: Prepare for release of NWB schema 2.8.0

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/matnwb#628]
### What would you like to see added to MatNWB?

NWB schema 2.8.0 is planned for release this week (ideally tomorrow).

Can you check that MatNWB works with this schema before release? It is available on this branch: https://github.com/NeurodataWithoutBorders/nwb-schema/pull/597

Here is the changelog from 2.7.0:

### Major changes
- Deprecated ``EventWaveform`` neurodata type.
- Deprecated ``ImageMaskSeries`` neurodata type.

### Minor changes
- Added optional ``was_generated_by`` attribute to ``NWBFile`` to store provenance information.
- Made ``band_mean`` and ``band_std`` in ``DecompositionSeries`` optional.
- Added ``Device.model_number``, ``Device.model_name``, ``Device.serial_number``.

### What solution would you like?

Verification that MatNWB will work with NWB schema 2.8.0

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/matnwb/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

**Comment by ehennestad** [comment]
https://github.com/NeurodataWithoutBorders/matnwb/pull/630

All test pass except for one which depends on pynwb being updated to work with nwb 2.8.0 schemas
