### ISSUE TITLE
RegionView help

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#63]
I'm working on adding spike times to the tutorial and I am running into RegionView issues. I get the following error:

```
Error using nwbfile/export (line 46)
Could not resolve paths for the following reference(s):
    /processing/cellular/my_spike_times/spike_times_index

Error in nwbExport (line 34)
    export(nwb(i), fn);

Error in ecephys (line 210)
nwbExport(nwb, 'ecephys_tutorial.nwb')
```
The section of interest is here:
https://github.com/NeurodataWithoutBorders/matnwb/blob/2f9f074952e1a9bcdaee61a8d79952797b23407a/tutorials/ecephys.m#L191

I think this error is probably my fault but I don't know what I'm doing wrong. Could you take a look at it for me?

**Comment by ln-vidrio** [comment]
88920b0

Also, if indexing vector data, you can omit the size argument a la:
```
types.untyped.RegionView(spike_loc, 1:bounds(2));
```
Size is now only required for multidimensional indices.
