### ISSUE TITLE
working dir dependency

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#69]
Some matnwb functions require that the working directory is matnwb, and this can be cumbersome when using other tools (especially if those other tools also have a requirement of a different working directory). Would it be possible to alter functions like `generateExtension` so that they work no matter where you run them? Could we use environmental variables for this?

**Comment by ln-vidrio** [comment]
I know that `generateCore`  works outside the matnwb directory if you add matnwb to the path.  What functions are you using?

**Comment by bendichter** [comment]
I've been having issues with `generateExtension` creating a `namespaces` dir in random directories.

**Comment by ln-vidrio** [comment]
`generateExtension` will always create a `namespaces` directory in the current directory where you called it.  Would it make more sense for it to be stored in the matnwb directory itself?

**Comment by bendichter** [comment]
I took the fact that `namespaces` is plural to imply that it holds multiple namespaces, which means extensions in addition to core. I also think that's more convenient that way. Maybe we could offer an override, but I think it makes sense to write extensions to matnwb/namespaces by default.

Also, when I try to run `generateExtension` in a random directory, I get the following error:

```matlab
Error using load
'./namespaces/core.mat' is not found in the
current folder or on the MATLAB path, but exists
in:
    /Users/bendichter/dev/matnwb

Change the MATLAB current folder or add its
folder to the MATLAB path.

Error in schemes.loadNamespace (line 8)
namespace = load(schemaPath);

Error in schemes.loadNamespace (line 24)
        extNamespaces = [extNamespaces;
        schemes.loadNamespace(depname,
        extNamespaces)];

Error in generateExtension (line 38)
extmap = schemes.loadNamespace(extSchema.name);
```

**Comment by bendichter** [comment]
I think so

**Comment by ln-vidrio** [comment]
be7be5e5b36aab738b53fa61a0c50d5e12a40114
So this is fixed for namespaces but the classes are still generated in the working directory as it breaks tests in a strange way.

**Comment by bendichter** [comment]
ok
