### ISSUE TITLE
Assigning a vector to a dataset with multiple shapes throws an error

### ISSUE THREAD

**Issue by mcafaro** [NeurodataWithoutBorders/matnwb#7]
Datasets that have multiple possible shapes including a vector shape cannot be assigned vector values:
```matlab
>> mc = testpack.TestClass(); 
>> mc.testDataset = 1;  % testDataset should accept a vector shape but it won't allow it
Error using testpack.TestClass/validate_testDataset (line 47)
TestClass.testDataset: val must have shape [2,3]

Error in testpack.TestClass/set.testDataset (line 26)
      obj.testDataset = validate_testDataset(obj, val);
```
This issue may be related to the use of ndims in the validation function. ndims will always return a value greater than or equal to 2, per https://www.mathworks.com/help/matlab/ref/ndims.html. The validation function assumes ndims will return 1 on a scalar value.

***Failing test:***
```matlab
>> nwbtest('ProcedureName', 'testWriteDatasetWithMultipleShapes')
```

**Comment by ln-vidrio** [comment]
Fixed
new test under
`>> nwbtest('ProcedureName', 'testMultipleShapesDataset')`
