### ISSUE TITLE
timestamp_reference_time schema change

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/matnwb#79]
https://github.com/NeurodataWithoutBorders/pynwb/pull/709 added the timestamp_reference_time field which should be set to the same value as session_start_time by default. Also, these fields use isodatetime as dtype in the schema which was added in ttps://github.com/NeurodataWithoutBorders/pynwb/pull/641, just in case MatNWB does not support this yet/

**Comment by bendichter** [comment]
The ecephys tutorial gives the following error:

```matlab
Error using types.core.NWBFile/export (line 693)
Property `timestamps_reference_time` is required.

Error in nwbfile/export (line 33)
                refs = export@types.core.NWBFile(obj, fid,
                '/', {});

Error in nwbExport (line 34)
    export(nwb(i), fn);

Error in ecephys (line 196)
nwbExport(nwb, 'ecephys_tutorial.nwb')
```

The code in python to fix this is in `NWBFile.__init__`:

```python
if self.__timestamps_reference_time is None:
    self.__timestamps_reference_time = self.__session_start_time
```

**Comment by ln-vidrio** [comment]
This work?
c3f684da34cf3e1e4fd8c0aec32672fc2d2c2514

**Comment by bendichter** [comment]
yup!
