### ISSUE TITLE
Use char array instead of cellstr for text dtype

### ISSUE THREAD

**Issue by mcafaro** [NeurodataWithoutBorders/matnwb#8]
Why is cellstr used for text dtypes? It seems like a string would be more natural.

For example, why do I have to do this:
```matlab
>> ts = types.TimeSeries;
>> ts.source = {'hello'}
```
Instead of this:
```matlab
>> ts.source = 'hello'
```

**Comment by ln-vidrio** [comment]
As of 418f8e6180c096aba530320c956dfd2820598090, matnwb should be converting char arrays to scalar text and cellstr to text arrays (and vice versa).
