### ISSUE TITLE
Attribute.value should be a constant value

### ISSUE THREAD

**Issue by mcafaro** [NeurodataWithoutBorders/matnwb#9]
The spec says the Attribute.value key should be assigned a constant value for an attribute (see http://schema-language.readthedocs.io/en/latest/specification_language_description.html#value ). However, it is mapped as only a default value for a property that can be changed.

***Failing test:***
```matlab
>> nwbtest('ProcedureName', 'testWriteAttributeWithValue')
```

**Comment by ln-vidrio** [comment]
Apparently there are minor usability issues if you require that a property be readonly but required.  That said, 418f8e6180c096aba530320c956dfd2820598090 should do this.
