### ISSUE TITLE
MATLAB table -> NWB DynamicTable converter

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#98]
We have a function `util.table2nwb` that takes in a MATLAB table and outputs an matnwb `DynamicTable` that can be directly added to an `NWBFile` object. This is a start, but is not fully functional enough to be used for all common table needs, like writing the `units` table. Here is a list of features that are needed:

- [x]  take as input a MATLAB table object and output an NWB table
- [ ]  create an indexed column for columns that have varying length arrays (`util.create_indexed_column` might be useful here)
- [ ]  handle `DynamicTableRegion`s (and indexed `DynamicTableRegion`s)
- [ ]  wrapper functions for default tables (`electrodes`, `units`, `trials`, `invalid_times`, etc.) that handle default columns correctly
- [ ]  tests
	- [ ]  test for round trip in MATLAB
	- [ ]  test for read in pynwb
- [ ]  documentation
	- [ ]  function comments
	- [ ]  incorporating into tutorials

How to do each of these is demonstrated here:

https://github.com/NeurodataWithoutBorders/matnwb/blob/fa4f8bdbd6f22cadca6f2d24901309d623a10947/tutorials/ecephys.m#L143-L225

**Comment by ln-vidrio** [comment]
Do we eventually want this to be integrated into read/write?

**Comment by bendichter** [comment]
I was imagining a one-line convert command before write, but I think integrating it in directly could be nice too.

**Comment by ln-vidrio** [comment]
There used to be a way to manually extend matNWB classes.  I don't think that's around anymore but you would do that for all relevant dynamic table classes and basically have it run util.table2nwb() right before exporting normally.  That might be farther down the line though.

**Comment by bendichter** [comment]
OK, sounds good. I like the idea of having the ability to extend matNWB classes. Having `to_table()` as a method, for instance, would be really nice.

**Comment by ln-vidrio** [comment]
One of the inputs of the DynamicTable GetRow/AddRow #267  supports tables as well. In fact, adding a full table to an DynamicTable will convert the table to its equivalent DynamicTable type. Indexing is also supported here.
